// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Integration tests for Kokoro segment export and import.
//!
//! Validates that each of the 5 Kokoro pipeline segments can be imported
//! via `import_model()` from torch.export `graph.json` + `weights.safetensors`.
//!
//! Segment layout (from designs/2026-03-29-kokoro-segment-export.md):
//!
//! - **PlBert** (Segment 0): ALBERT encoder + bert_encoder Linear.
//!   Inputs: input_ids [B,T], position_ids [T], token_type_ids [T].
//!   Output: bert_features [B, 512, T].
//!
//! - **TextEncoder** (Segment 1): Embedding + Conv1d + BiLSTM + Linear.
//!   Input: input_ids [B, T].
//!   Output: text_features [B, 512, T].
//!
//! - **ProsodyPredictor** (Segment 2): DurationEncoder (4x BiLSTM + AdaLayerNorm) + proj.
//!   Inputs: bert_features [B, 512, T], style [B, 128].
//!   Outputs: dur_logits [B, T, 50], features [B, 640, T].
//!
//! - **F0EnergyPredictor** (Segment 3): Shared BiLSTM + F0/Energy heads (AdainResBlk1d).
//!   Inputs: aligned_dur [B, 640, T_mel], style [B, 128].
//!   Outputs: f0 [B, 1, 2*T_mel], energy [B, 1, 2*T_mel].
//!
//! - **Decoder** (Segment 4): AdaIN ResBlks + ISTFTNet generator. Already exported.
//!   Inputs: x [B, 512, T], style [B, 128], har_source [B, 2*n_bins, T_stft].
//!   Outputs: magnitude [B, n_bins, T_out], phase [B, n_bins, T_out].
//!
//! Tests skip gracefully when model files are not present (they must be
//! generated by `crates/nn-import/python/export_kokoro_segments.py`).

// Tests are cfg-gated; helpers may appear unused without features.
#![allow(dead_code)]

use std::path::{Path, PathBuf};

use nn_import::import_model;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

fn segment_dir(segment: &str) -> PathBuf {
    workspace_root()
        .join("models")
        .join("kokoro-82m")
        .join(segment)
}

/// Returns `true` if `graph.json` and `weights.safetensors` exist for a segment.
/// Prints a skip message and returns `false` otherwise.
fn require_segment_files(segment: &str) -> Option<(PathBuf, PathBuf)> {
    let dir = segment_dir(segment);
    let graph = dir.join("graph.json");
    let weights = dir.join("weights.safetensors");

    if !graph.exists() || !weights.exists() {
        eprintln!(
            "SKIP: Kokoro segment '{}' model files not found at {}",
            segment,
            dir.display()
        );
        return None;
    }
    Some((graph, weights))
}

/// Import a segment and run basic structural assertions.
fn import_and_validate(
    segment: &str,
    expected_min_inputs: usize,
    expected_min_outputs: usize,
) -> Option<nn_import::ImportedGraph> {
    let (graph_path, weights_path) = require_segment_files(segment)?;

    let imported = import_model(&graph_path, &weights_path)
        .unwrap_or_else(|e| panic!("import_model failed for segment '{segment}': {e:?}"));

    let node_count = imported.graph.nodes().len();
    assert!(
        node_count > 0,
        "segment '{segment}': expected > 0 nodes, got 0"
    );

    assert!(
        imported.num_user_inputs >= expected_min_inputs,
        "segment '{}': expected >= {} user inputs, got {}",
        segment,
        expected_min_inputs,
        imported.num_user_inputs
    );

    assert!(
        imported.output_names.len() >= expected_min_outputs,
        "segment '{}': expected >= {} outputs, got {}",
        segment,
        expected_min_outputs,
        imported.output_names.len()
    );

    eprintln!(
        "Kokoro segment '{}': {} nodes, {} user inputs {:?}, {} outputs {:?}",
        segment,
        node_count,
        imported.num_user_inputs,
        imported.user_input_names,
        imported.output_names.len(),
        imported.output_names
    );

    Some(imported)
}

// ---------------------------------------------------------------------------
// Segment 0: PlBert + bert_encoder
// ---------------------------------------------------------------------------

/// Import PlBert segment and validate structure.
///
/// PlBert is a standard ALBERT encoder (12 shared layers) followed by a
/// Linear(768, 512) projection + transpose. Expected ops: Embedding, Linear,
/// LayerNorm, SDPA/MatMul, GELU, Add, Transpose, Reshape.
///
/// Inputs: input_ids [B,T], position_ids [T], token_type_ids [T] (3 inputs).
/// Output: bert_features [B, 512, T] (1 output).
#[test]
fn test_plbert_import() {
    let imported = match import_and_validate("plbert", 1, 1) {
        Some(g) => g,
        None => return,
    };

    // PlBert has at least 3 inputs (input_ids, position_ids, token_type_ids).
    // The actual count depends on how torch.export handles the attention_mask.
    assert!(
        imported.num_user_inputs >= 1,
        "PlBert should have >= 1 user input, got {}",
        imported.num_user_inputs
    );

    // Validate input names look reasonable (should reference ids/embeddings).
    for name in &imported.user_input_names {
        eprintln!("  PlBert input: '{name}'");
    }

    eprintln!("PlBert import: PASSED");
}

/// L2: NY IBP proof for PlBert segment.
#[test]
#[cfg(feature = "verify")]
fn test_plbert_gamma_crown_proof() {
    let (graph_path, weights_path) = match require_segment_files("plbert") {
        Some(paths) => paths,
        None => return,
    };

    let imported = import_model(&graph_path, &weights_path)
        .unwrap_or_else(|e| panic!("import_model failed for plbert: {e:?}"));

    let report = nn_import::check_composition_bounds(&imported);
    let report = match report {
        Some(r) => r,
        None => {
            eprintln!("SKIP: PlBert L2 proof — NY returned None (unsupported ops)");
            return;
        }
    };

    assert!(report.propagation_ok, "PlBert: IBP propagation failed");
    if let Some(width) = report.output_width {
        eprintln!("PlBert L2: output bound width = {width:.4}");
    }
    eprintln!("PlBert L2: NY IBP proof PASSED");
}

// ---------------------------------------------------------------------------
// Segment 1: TextEncoder
// ---------------------------------------------------------------------------

/// Import TextEncoder segment and validate structure.
///
/// TextEncoder: Embedding(178, 512) + 3x Conv1d(512, 512, k=5) + BiLSTM(512, 256)
///   + Linear(512, 512). Expected ops: Embedding, Conv1d, LayerNorm, LeakyReLU,
///   LSTM, Linear, Transpose, Permute.
///
/// Input: input_ids [B, T] (1 user input, possibly more for lengths/mask).
/// Output: text_features [B, 512, T] (1 output).
#[test]
fn test_text_encoder_import() {
    let imported = match import_and_validate("text_encoder", 1, 1) {
        Some(g) => g,
        None => return,
    };

    use nn_core::dyn_tensor::trace::TraceOp;
    let nodes = imported.graph.nodes();

    // TextEncoder should have Conv1d ops (3 convolution layers).
    let conv1d_count = nodes
        .iter()
        .filter(|n| matches!(n.op(), TraceOp::Conv1d { .. }))
        .count();
    eprintln!("  TextEncoder Conv1d count: {conv1d_count}");

    // TextEncoder has a BiLSTM which may appear as LSTM or decomposed ops.
    // Check for either LSTM or the typical decomposed pattern (many Linear ops).
    let linear_count = nodes
        .iter()
        .filter(|n| matches!(n.op(), TraceOp::Linear { .. }))
        .count();
    eprintln!("  TextEncoder Linear count: {linear_count}");

    eprintln!("TextEncoder import: PASSED");
}

/// L2: NY IBP proof for TextEncoder segment.
#[test]
#[cfg(feature = "verify")]
fn test_text_encoder_gamma_crown_proof() {
    let (graph_path, weights_path) = match require_segment_files("text_encoder") {
        Some(paths) => paths,
        None => return,
    };

    let imported = import_model(&graph_path, &weights_path)
        .unwrap_or_else(|e| panic!("import_model failed for text_encoder: {e:?}"));

    let report = nn_import::check_composition_bounds(&imported);
    let report = match report {
        Some(r) => r,
        None => {
            eprintln!("SKIP: TextEncoder L2 proof — NY returned None (unsupported ops)");
            return;
        }
    };

    assert!(report.propagation_ok, "TextEncoder: IBP propagation failed");
    if let Some(width) = report.output_width {
        eprintln!("TextEncoder L2: output bound width = {width:.4}");
    }
    eprintln!("TextEncoder L2: NY IBP proof PASSED");
}

// ---------------------------------------------------------------------------
// Segment 2: ProsodyPredictor
// ---------------------------------------------------------------------------

/// Import ProsodyPredictor segment and validate structure.
///
/// ProsodyPredictor: DurationEncoder (3x [BiLSTM + AdaLayerNorm]) + duration BiLSTM
/// + Linear(512, 50). Multi-output: dur_logits [B, T, 50] + features [B, 640, T].
///
/// Inputs: bert_features [B, 512, T], style [B, 128] (2 inputs).
/// Outputs: dur_logits [B, T, 50], features [B, 640, T] (2 outputs).
#[test]
fn test_prosody_import() {
    let imported = match import_and_validate("prosody", 2, 2) {
        Some(g) => g,
        None => return,
    };

    // ProsodyPredictor has 2 inputs: bert_features and style.
    assert!(
        imported.num_user_inputs >= 2,
        "ProsodyPredictor should have >= 2 user inputs (bert_features, style), got {}",
        imported.num_user_inputs
    );

    // ProsodyPredictor has 2 outputs: dur_logits and features.
    assert!(
        imported.output_names.len() >= 2,
        "ProsodyPredictor should have >= 2 outputs (dur_logits, features), got {}",
        imported.output_names.len()
    );

    eprintln!("ProsodyPredictor import: PASSED");
}

/// L2: NY IBP proof for ProsodyPredictor segment.
#[test]
#[cfg(feature = "verify")]
fn test_prosody_gamma_crown_proof() {
    let (graph_path, weights_path) = match require_segment_files("prosody") {
        Some(paths) => paths,
        None => return,
    };

    let imported = import_model(&graph_path, &weights_path)
        .unwrap_or_else(|e| panic!("import_model failed for prosody: {e:?}"));

    let report = nn_import::check_composition_bounds(&imported);
    let report = match report {
        Some(r) => r,
        None => {
            eprintln!(
                "SKIP: ProsodyPredictor L2 proof — NY returned None (unsupported ops)"
            );
            return;
        }
    };

    assert!(
        report.propagation_ok,
        "ProsodyPredictor: IBP propagation failed"
    );
    if let Some(width) = report.output_width {
        eprintln!("ProsodyPredictor L2: output bound width = {width:.4}");
    }
    eprintln!("ProsodyPredictor L2: NY IBP proof PASSED");
}

// ---------------------------------------------------------------------------
// Segment 3: F0EnergyPredictor
// ---------------------------------------------------------------------------

/// Import F0EnergyPredictor segment and validate structure.
///
/// F0EnergyPredictor: shared BiLSTM(640, 256) + F0 head (3x AdainResBlk1d + Conv1d)
/// + Energy head (3x AdainResBlk1d + Conv1d). Multi-output with 2x upsample.
///
/// Inputs: aligned_dur [B, 640, T_mel], style [B, 128] (2 inputs).
/// Outputs: f0 [B, 1, 2*T_mel], energy [B, 1, 2*T_mel] (2 outputs).
#[test]
fn test_f0_energy_import() {
    let imported = match import_and_validate("f0_energy", 2, 2) {
        Some(g) => g,
        None => return,
    };

    // F0EnergyPredictor has 2 inputs: aligned_dur and style.
    assert!(
        imported.num_user_inputs >= 2,
        "F0EnergyPredictor should have >= 2 user inputs (aligned_dur, style), got {}",
        imported.num_user_inputs
    );

    // F0EnergyPredictor has 2 outputs: f0 and energy.
    assert!(
        imported.output_names.len() >= 2,
        "F0EnergyPredictor should have >= 2 outputs (f0, energy), got {}",
        imported.output_names.len()
    );

    use nn_core::dyn_tensor::trace::TraceOp;
    let nodes = imported.graph.nodes();

    // Should have Conv1d ops from the AdainResBlk1d blocks and projection heads.
    let conv1d_count = nodes
        .iter()
        .filter(|n| matches!(n.op(), TraceOp::Conv1d { .. }))
        .count();
    eprintln!("  F0EnergyPredictor Conv1d count: {conv1d_count}");

    // Should have ConvTranspose1d for upsampling (block 1 in each head upsamples 2x).
    let conv_t_count = nodes
        .iter()
        .filter(|n| matches!(n.op(), TraceOp::ConvTranspose1d { .. }))
        .count();
    eprintln!(
        "  F0EnergyPredictor ConvTranspose1d count: {conv_t_count}"
    );

    // Should have InstanceNorm from AdaIN decomposition.
    let instnorm_count = nodes
        .iter()
        .filter(|n| matches!(n.op(), TraceOp::InstanceNorm { .. }))
        .count();
    eprintln!("  F0EnergyPredictor InstanceNorm count: {instnorm_count}");

    eprintln!("F0EnergyPredictor import: PASSED");
}

/// L2: NY IBP proof for F0EnergyPredictor segment.
#[test]
#[cfg(feature = "verify")]
fn test_f0_energy_gamma_crown_proof() {
    let (graph_path, weights_path) = match require_segment_files("f0_energy") {
        Some(paths) => paths,
        None => return,
    };

    let imported = import_model(&graph_path, &weights_path)
        .unwrap_or_else(|e| panic!("import_model failed for f0_energy: {e:?}"));

    let report = nn_import::check_composition_bounds(&imported);
    let report = match report {
        Some(r) => r,
        None => {
            eprintln!(
                "SKIP: F0EnergyPredictor L2 proof — NY returned None (unsupported ops)"
            );
            return;
        }
    };

    assert!(
        report.propagation_ok,
        "F0EnergyPredictor: IBP propagation failed"
    );
    if let Some(width) = report.output_width {
        eprintln!("F0EnergyPredictor L2: output bound width = {width:.4}");
    }
    eprintln!("F0EnergyPredictor L2: NY IBP proof PASSED");
}

// ---------------------------------------------------------------------------
// Segment 4: Decoder (already exported — included for completeness)
// ---------------------------------------------------------------------------

/// Import the decoder segment and validate structure.
///
/// The decoder is already exported at `models/kokoro-82m/decoder/`.
/// This test mirrors `kokoro_decoder_import.rs` but is included here
/// so all 5 segments are tested in one file.
///
/// Inputs: x [B, 512, T], style [B, 128], har_source [B, 2*n_bins, T_stft] (3 inputs).
/// Outputs: magnitude [B, n_bins, T_out], phase [B, n_bins, T_out] (2 outputs).
#[test]
fn test_decoder_import() {
    let imported = match import_and_validate("decoder", 3, 2) {
        Some(g) => g,
        None => return,
    };

    use nn_core::dyn_tensor::trace::TraceOp;
    let nodes = imported.graph.nodes();

    // Decoder: 3 inputs (x, s, har), 2 outputs (spec, phase).
    assert_eq!(
        imported.num_user_inputs, 3,
        "decoder has 3 inputs (x, style, har_source)"
    );
    assert_eq!(
        imported.output_names.len(),
        2,
        "decoder has 2 outputs (magnitude, phase)"
    );

    // Conv1d: >= 40 (noise_convs + resblock convs + conv_post).
    let conv1d = nodes
        .iter()
        .filter(|n| matches!(n.op(), TraceOp::Conv1d { .. }))
        .count();
    assert!(conv1d >= 40, "expected >= 40 Conv1d ops, got {conv1d}");

    // ConvTranspose1d: 2 upsample layers.
    let conv_t = nodes
        .iter()
        .filter(|n| matches!(n.op(), TraceOp::ConvTranspose1d { .. }))
        .count();
    assert_eq!(
        conv_t, 2,
        "expected 2 ConvTranspose1d (2 upsampling stages)"
    );

    // InstanceNorm: >= 40 from AdaIN1d blocks.
    let instnorm = nodes
        .iter()
        .filter(|n| matches!(n.op(), TraceOp::InstanceNorm { .. }))
        .count();
    assert!(
        instnorm >= 40,
        "expected >= 40 InstanceNorm ops (AdaIN), got {instnorm}"
    );

    eprintln!("Decoder import: PASSED");
}

/// L2: NY IBP proof for decoder segment.
///
/// This is the same proof as in `kokoro_decoder_convert.rs` but included
/// here for cross-segment completeness.
#[test]
#[cfg(feature = "verify")]
fn test_decoder_gamma_crown_proof() {
    let (graph_path, weights_path) = match require_segment_files("decoder") {
        Some(paths) => paths,
        None => return,
    };

    let imported = import_model(&graph_path, &weights_path)
        .unwrap_or_else(|e| panic!("import_model failed for decoder: {e:?}"));

    let report = nn_import::check_composition_bounds(&imported);
    let report = match report {
        Some(r) => r,
        None => {
            eprintln!("SKIP: Decoder L2 proof — NY returned None");
            return;
        }
    };

    assert!(report.propagation_ok, "Decoder: IBP propagation failed");
    if let Some(width) = report.output_width {
        assert!(
            width.is_finite(),
            "Decoder: output bound width is non-finite: {width}"
        );
        eprintln!("Decoder L2: output bound width = {width:.4}");
    }
    eprintln!("Decoder L2: NY IBP proof PASSED");
}

// ---------------------------------------------------------------------------
// L3: Reference parity tests (require Metal GPU + reference.safetensors)
// ---------------------------------------------------------------------------

/// L3: Reference parity for PlBert segment.
#[test]
#[cfg(all(feature = "metal", feature = "reftest", target_os = "macos"))]
fn test_plbert_reference_parity() {
    let dir = segment_dir("plbert");
    let graph = dir.join("graph.json");
    let weights = dir.join("weights.safetensors");
    let reference = dir.join("reference.safetensors");

    if !graph.exists() || !weights.exists() || !reference.exists() {
        eprintln!(
            "SKIP: PlBert L3 parity — model or reference files not found at {}",
            dir.display()
        );
        return;
    }

    let _ = nn_metal::MetalBackend::init();
    nn_metal::register_metal_dyn_backend();
    let cache = nn_metal::PipelineCache::new(
        nn_metal::MetalContext::new().expect("Metal device required"),
    );

    let result = nn_import::convert(&graph, &weights, Some(&reference), &cache)
        .unwrap_or_else(|e| panic!("convert() failed for plbert: {e:?}"));

    let parity = result
        .proof
        .reference_parity
        .expect("reference parity should be available");
    assert!(
        parity.divergence.all_passed,
        "PlBert L3 parity failed: {:?}",
        parity.divergence
    );
    eprintln!("PlBert L3: reference parity PASSED");
}

/// L3: Reference parity for TextEncoder segment.
#[test]
#[cfg(all(feature = "metal", feature = "reftest", target_os = "macos"))]
fn test_text_encoder_reference_parity() {
    let dir = segment_dir("text_encoder");
    let graph = dir.join("graph.json");
    let weights = dir.join("weights.safetensors");
    let reference = dir.join("reference.safetensors");

    if !graph.exists() || !weights.exists() || !reference.exists() {
        eprintln!(
            "SKIP: TextEncoder L3 parity — model or reference files not found at {}",
            dir.display()
        );
        return;
    }

    let _ = nn_metal::MetalBackend::init();
    nn_metal::register_metal_dyn_backend();
    let cache = nn_metal::PipelineCache::new(
        nn_metal::MetalContext::new().expect("Metal device required"),
    );

    let result = nn_import::convert(&graph, &weights, Some(&reference), &cache)
        .unwrap_or_else(|e| panic!("convert() failed for text_encoder: {e:?}"));

    let parity = result
        .proof
        .reference_parity
        .expect("reference parity should be available");
    assert!(
        parity.divergence.all_passed,
        "TextEncoder L3 parity failed: {:?}",
        parity.divergence
    );
    eprintln!("TextEncoder L3: reference parity PASSED");
}

/// L3: Reference parity for ProsodyPredictor segment.
#[test]
#[cfg(all(feature = "metal", feature = "reftest", target_os = "macos"))]
fn test_prosody_reference_parity() {
    let dir = segment_dir("prosody");
    let graph = dir.join("graph.json");
    let weights = dir.join("weights.safetensors");
    let reference = dir.join("reference.safetensors");

    if !graph.exists() || !weights.exists() || !reference.exists() {
        eprintln!(
            "SKIP: ProsodyPredictor L3 parity — model or reference files not found at {}",
            dir.display()
        );
        return;
    }

    let _ = nn_metal::MetalBackend::init();
    nn_metal::register_metal_dyn_backend();
    let cache = nn_metal::PipelineCache::new(
        nn_metal::MetalContext::new().expect("Metal device required"),
    );

    let result = nn_import::convert(&graph, &weights, Some(&reference), &cache)
        .unwrap_or_else(|e| panic!("convert() failed for prosody: {e:?}"));

    let parity = result
        .proof
        .reference_parity
        .expect("reference parity should be available");
    assert!(
        parity.divergence.all_passed,
        "ProsodyPredictor L3 parity failed: {:?}",
        parity.divergence
    );
    eprintln!("ProsodyPredictor L3: reference parity PASSED");
}

/// L3: Reference parity for F0EnergyPredictor segment.
#[test]
#[cfg(all(feature = "metal", feature = "reftest", target_os = "macos"))]
fn test_f0_energy_reference_parity() {
    let dir = segment_dir("f0_energy");
    let graph = dir.join("graph.json");
    let weights = dir.join("weights.safetensors");
    let reference = dir.join("reference.safetensors");

    if !graph.exists() || !weights.exists() || !reference.exists() {
        eprintln!(
            "SKIP: F0EnergyPredictor L3 parity — model or reference files not found at {}",
            dir.display()
        );
        return;
    }

    let _ = nn_metal::MetalBackend::init();
    nn_metal::register_metal_dyn_backend();
    let cache = nn_metal::PipelineCache::new(
        nn_metal::MetalContext::new().expect("Metal device required"),
    );

    let result = nn_import::convert(&graph, &weights, Some(&reference), &cache)
        .unwrap_or_else(|e| panic!("convert() failed for f0_energy: {e:?}"));

    let parity = result
        .proof
        .reference_parity
        .expect("reference parity should be available");
    assert!(
        parity.divergence.all_passed,
        "F0EnergyPredictor L3 parity failed: {:?}",
        parity.divergence
    );
    eprintln!("F0EnergyPredictor L3: reference parity PASSED");
}
