// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Canonical short names for `TraceOp` variants.
//!
//! Extracted from `trace_op_class.rs` to keep that file under the 450-line
//! limit as new variants are added. Single source of truth for op naming,
//! used by both the compile path (nn-dsl) and verify path (nn-verify).

use super::{KokoroFusedOp, TraceOp};

impl TraceOp {
    /// Returns a canonical short name for the operation.
    ///
    /// This is the single source of truth for op naming, used by both
    /// the compile path (nn-dsl) and the verify path (nn-verify).
    /// Unlike `op_prefix()` (which is `pub(super)`), this is public API.
    #[must_use]
    #[allow(unreachable_patterns)] // #[non_exhaustive] catch-all for future variants
    pub fn canonical_name(&self) -> &str {
        match self {
            Self::Input => "input",
            Self::Add => "add",
            Self::Sub => "sub",
            Self::Mul => "mul",
            Self::Div => "div",
            Self::Maximum => "maximum",
            Self::Minimum => "minimum",
            Self::MatMul => "matmul",
            Self::Relu => "relu",
            Self::Gelu | Self::GeluErf => "gelu",
            Self::Silu => "silu",
            Self::Tanh => "tanh",
            Self::Sigmoid => "sigmoid",
            Self::Exp => "exp",
            Self::Log => "log",
            Self::Sqrt => "sqrt",
            Self::Sqr => "sqr",
            Self::Abs => "abs",
            Self::Neg => "neg",
            Self::Recip => "recip",
            Self::Sin => "sin",
            Self::Cos => "cos",
            Self::Floor => "floor",
            Self::Round => "round",
            Self::Fract => "fract",
            Self::ToDtype { .. } => "to_dtype",
            Self::Flip { .. } => "flip",
            Self::Roll { .. } => "roll",
            Self::Unfold { .. } => "unfold",
            Self::SliceSet { .. } => "slice_set",
            Self::Scatter { .. } => "scatter",
            Self::ScatterAdd { .. } => "scatter_add",
            Self::IndexAdd { .. } => "index_add",
            Self::IndexPut { .. } => "index_put",
            Self::ReduceSum { .. } => "reduce_sum",
            Self::ReduceMean { .. } => "reduce_mean",
            Self::ReduceMax { .. } => "reduce_max",
            Self::ReduceMin { .. } => "reduce_min",
            Self::Reshape { .. } => "reshape",
            Self::Transpose { .. } => "transpose",
            Self::Narrow { .. } => "narrow",
            Self::Unsqueeze { .. } => "unsqueeze",
            Self::Squeeze { .. } => "squeeze",
            Self::Permute { .. } => "permute",
            Self::Cat { .. } => "cat",
            Self::LayerNorm { .. } => "layer_norm",
            Self::RmsNorm { .. } => "rms_norm",
            Self::GroupNorm { .. } => "group_norm",
            Self::InstanceNorm { .. } => "instance_norm",
            Self::BatchNorm { .. } => "batch_norm",
            Self::Linear { .. } => "linear",
            Self::Conv1d { .. } => "conv1d",
            Self::Conv2d { .. } => "conv2d",
            Self::Conv3d { .. } => "conv3d",
            Self::ConvTranspose1d { .. } => "conv_transpose1d",
            Self::ConvTranspose2d { .. } => "conv_transpose2d",
            Self::Softmax { .. } => "softmax",
            Self::LogSoftmax { .. } => "log_softmax",
            Self::Sdpa { .. } => "sdpa",
            Self::SdpaCausal { .. } => "sdpa_causal",
            Self::RotaryEmbedding { .. } => "rope",
            Self::MultiHeadAttention { .. } => "mha",
            Self::Embedding { .. } => "embedding",
            Self::Lstm { .. } => "lstm",
            Self::MaxPool1d { .. } => "max_pool1d",
            Self::AvgPool2d { .. } => "avg_pool2d",
            Self::MaxPool2d { .. } => "max_pool2d",
            Self::AdaptiveAvgPool2d { .. } => "adaptive_avg_pool2d",
            Self::AvgPool1d { .. } => "avg_pool1d",
            Self::AdaptiveAvgPool1d { .. } => "adaptive_avg_pool1d",
            Self::AdaptiveMaxPool2d { .. } => "adaptive_max_pool2d",
            Self::Activation { kind } => kind.as_str(),
            Self::Elu { .. } => "elu",
            Self::LeakyRelu { .. } => "leaky_relu",
            Self::Softplus => "softplus",
            Self::KokoroFused(ref fused) => match fused {
                KokoroFusedOp::SnakeTensor { .. } => "snake_tensor",
                KokoroFusedOp::AdainSnake { .. } => "adain_snake",
                KokoroFusedOp::AdainLeakyRelu { .. } => "adain_leaky_relu",
                KokoroFusedOp::AdaLayerNorm { .. } => "ada_layer_norm",
                KokoroFusedOp::FusedAdainResBlock { .. } => "fused_adain_resblock",
                _ => "<unknown_kokoro_fused>",
            },
            Self::SwiGlu => "swiglu",
            Self::Dropout => "dropout",
            Self::PixelShuffle { .. } => "pixel_shuffle",
            Self::PixelUnshuffle { .. } => "pixel_unshuffle",
            Self::Upsample1d { .. } => "upsample1d",
            Self::Upsample2d { .. } => "upsample2d",
            Self::ResizeBilinear { .. } => "resize_bilinear",
            Self::Triu { .. } => "triu",
            Self::Tril { .. } => "tril",
            Self::GridSample { .. } => "grid_sample",
            Self::QLinear { .. } => "qlinear",
            Self::Topk { .. } => "topk",
            Self::Argmax { .. } => "argmax",
            Self::Argmin { .. } => "argmin",
            Self::ArgSort { .. } => "arg_sort",
            Self::Sort { .. } => "sort",
            Self::IndexSelect { .. } => "index_select",
            Self::Gather { .. } => "gather",
            Self::WhereCond => "where_cond",
            Self::Expand { .. } => "expand",
            Self::Compare { .. } => "compare",
            Self::CompareTensor { .. } => "compare_tensor",
            Self::Cumsum { .. } => "cumsum",
            Self::RepeatInterleave { .. } => "repeat_interleave",
            Self::Powf { .. } => "powf",
            Self::Clamp { .. } => "clamp",
            Self::Constant { .. } => "constant",
            Self::ConstantWeight { .. } => "constant_weight",
            Self::ReflectionPad1d { .. } => "reflection_pad1d",
            Self::ReflectionPad2d { .. } => "reflection_pad2d",
            Self::ConstantPadNd { .. } => "constant_pad_nd",
            Self::Atan2 => "atan2",
            Self::Arange { .. } => "arange",
            Self::SegmentBoundary { .. } => "segment_boundary",
            Self::MoeGating { .. } => "moe_gating",
            Self::Custom { name } => name.as_str(),
            // #[non_exhaustive] catch-all — clearly invalid name so
            // missing arms are visible in error messages and logs.
            _ => "<unknown_trace_op>",
        }
    }
}
