[package]
name = "nn-cpu"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "CPU SIMD backend for nn"

[lints]
workspace = true

[dependencies]

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "matmul_bench"
harness = false
