// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! PyTorch parity tests: load .npy reference tensors generated by
//! `scripts/generate_references.py` and compare against nn DynTensor ops.
//!
//! These tests gate on the existence of `test_data/references/`. If the
//! reference directory is missing, each test prints a skip message and returns
//! (no `#[ignore]` — see ait#341).
//!
//! Tolerance bands:
//! - Exact ops (relu, add, sub, mul, reshape, transpose, cat): 1e-6
//! - Numerically sensitive ops (gelu, silu, sigmoid, tanh, softmax, exp, log,
//!   div, matmul, reductions, normalization): 1e-4

use std::path::{Path, PathBuf};

use nn_core::{Device, DynTensor, Module};
use nn_reftest::{compare_tensors, load_npy, ComparisonConfig, NamedTensor};

/// Root directory for PyTorch-generated reference tensors.
fn ref_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("test_data")
        .join("references")
}

/// Return `true` if the reference directory exists and the test should run.
/// Prints a skip message otherwise.
fn refs_available(test_name: &str) -> bool {
    if ref_dir().is_dir() {
        true
    } else {
        eprintln!(
            "[SKIP] {test_name}: reference directory not found at {}. \
             Run `python3 scripts/generate_references.py` to generate.",
            ref_dir().display()
        );
        false
    }
}

/// Load a single .npy file into a flat `Vec<f32>` and its shape.
fn load_npy_tensor(path: &Path) -> (Vec<f32>, Vec<usize>) {
    let trace = load_npy(path).expect("failed to load npy");
    let t = trace.get(0).expect("npy trace should have one checkpoint");
    (t.data.clone(), t.shape.clone())
}

/// Load input_0.npy from a reference subdirectory.
fn load_input(dir: &Path) -> DynTensor {
    let (data, shape) = load_npy_tensor(&dir.join("input_0.npy"));
    DynTensor::from_vec(data, shape, &Device::Cpu).expect("valid input tensor")
}

/// Load input_N.npy from a reference subdirectory.
fn load_input_n(dir: &Path, n: usize) -> DynTensor {
    let (data, shape) = load_npy_tensor(&dir.join(format!("input_{n}.npy")));
    DynTensor::from_vec(data, shape, &Device::Cpu).expect("valid input tensor")
}

/// Load output_0.npy as a NamedTensor for comparison.
fn load_expected(dir: &Path, name: &str) -> NamedTensor {
    let (data, shape) = load_npy_tensor(&dir.join("output_0.npy"));
    NamedTensor::new(name, shape, data).expect("valid expected tensor")
}

/// Convert a DynTensor to a NamedTensor for comparison.
fn to_named(name: &str, t: &DynTensor) -> NamedTensor {
    let data = t.to_flat_vec::<f32>().expect("f32 extraction");
    let shape: Vec<usize> = (0..t.rank()).map(|d| t.dim(d).unwrap()).collect();
    NamedTensor::new(name, shape, data).expect("valid named tensor")
}

/// Assert parity between nn output and PyTorch reference within tolerance.
fn assert_parity(name: &str, actual: &DynTensor, expected: &NamedTensor, tol: f32) {
    let actual_named = to_named(name, actual);
    let config = ComparisonConfig::new(tol, tol, 0.9999);
    let result = compare_tensors(expected, &actual_named, &config)
        .unwrap_or_else(|e| panic!("{name}: comparison failed: {e}"));
    assert!(
        result.passed,
        "{name}: PyTorch parity FAILED\n  \
         max_abs_diff = {:.6e} (tol = {:.1e})\n  \
         max_rel_diff = {:.6e}\n  \
         cosine_similarity = {:.8}\n  \
         shape = {:?}, elements = {}",
        result.max_abs_diff,
        tol,
        result.max_rel_diff,
        result.cosine_similarity,
        result.shape,
        result.num_elements,
    );
}

// ---------------------------------------------------------------------------
// Elementwise operations
// ---------------------------------------------------------------------------

macro_rules! elementwise_test {
    ($name:ident, $op:ident, $tol:expr) => {
        elementwise_test!($name, $op, stringify!($op), $tol);
    };
    ($name:ident, $op:ident, $ref_name:expr, $tol:expr) => {
        #[test]
        fn $name() {
            let test_name = stringify!($name);
            if !refs_available(test_name) {
                return;
            }
            let dir = ref_dir().join("elementwise").join($ref_name);
            let input = load_input(&dir);
            let expected = load_expected(&dir, test_name);
            let actual = input
                .$op()
                .expect(concat!(stringify!($op), " should succeed"));
            assert_parity(test_name, &actual, &expected, $tol);
        }
    };
}

elementwise_test!(test_relu_parity, relu, 1e-6);
// PyTorch gelu() defaults to approximate='none' (erf-based), which matches
// nn's gelu_erf(). nn's gelu() uses the tanh approximation (2.3e-4 diff).
elementwise_test!(test_gelu_parity, gelu_erf, "gelu", 1e-4);
elementwise_test!(test_silu_parity, silu, 1e-4);
elementwise_test!(test_sigmoid_parity, sigmoid, 1e-4);
elementwise_test!(test_tanh_parity, tanh, 1e-4);
elementwise_test!(test_exp_parity, exp, 1e-4);

#[test]
fn test_softmax_parity() {
    let test_name = "test_softmax_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("elementwise").join("softmax");
    let input = load_input(&dir);
    let expected = load_expected(&dir, test_name);
    // PyTorch softmax was computed with dim=-1 (last dim).
    let actual = input
        .softmax(nn_core::D::Minus1)
        .expect("softmax should succeed");
    assert_parity(test_name, &actual, &expected, 1e-4);
}

#[test]
fn test_log_parity() {
    let test_name = "test_log_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("elementwise").join("log");
    // The Python script computed log(abs(x) + 1e-6), so we load the
    // pre-transformed input directly (input_0.npy is the raw x; PyTorch
    // applied abs+offset internally). We replicate the same transform.
    let (raw_data, shape) = load_npy_tensor(&dir.join("input_0.npy"));
    let expected = load_expected(&dir, test_name);
    let x = DynTensor::from_vec(raw_data, shape, &Device::Cpu).expect("valid tensor");
    let abs_x = x.abs().expect("abs");
    let shifted = abs_x.add_scalar(1e-6).expect("add_scalar");
    let actual = shifted.log().expect("log should succeed");
    assert_parity(test_name, &actual, &expected, 1e-4);
}

// ---------------------------------------------------------------------------
// Matmul
// ---------------------------------------------------------------------------

#[test]
fn test_matmul_basic_parity() {
    let test_name = "test_matmul_basic_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("matmul").join("basic");
    let a = load_input_n(&dir, 0);
    let b = load_input_n(&dir, 1);
    let expected = load_expected(&dir, test_name);
    let actual = a.matmul(&b).expect("matmul should succeed");
    assert_parity(test_name, &actual, &expected, 1e-4);
}

#[test]
fn test_matmul_batched_parity() {
    let test_name = "test_matmul_batched_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("matmul").join("batched");
    let a = load_input_n(&dir, 0);
    let b = load_input_n(&dir, 1);
    let expected = load_expected(&dir, test_name);
    let actual = a.matmul(&b).expect("batched matmul should succeed");
    assert_parity(test_name, &actual, &expected, 1e-4);
}

// ---------------------------------------------------------------------------
// Binary operations
// ---------------------------------------------------------------------------

macro_rules! binary_test {
    ($name:ident, $op:ident, $subdir:expr, $tol:expr) => {
        #[test]
        fn $name() {
            let test_name = stringify!($name);
            if !refs_available(test_name) {
                return;
            }
            let dir = ref_dir().join("binary").join($subdir);
            let a = load_input_n(&dir, 0);
            let b = load_input_n(&dir, 1);
            let expected = load_expected(&dir, test_name);
            let actual = a
                .$op(&b)
                .expect(concat!(stringify!($op), " should succeed"));
            assert_parity(test_name, &actual, &expected, $tol);
        }
    };
}

binary_test!(test_add_parity, add, "add", 1e-6);
binary_test!(test_sub_parity, sub, "sub", 1e-6);
binary_test!(test_mul_parity, mul, "mul", 1e-6);
binary_test!(test_div_parity, div, "div", 1e-4);
binary_test!(test_add_broadcast_parity, add, "add_broadcast", 1e-6);

// ---------------------------------------------------------------------------
// Reduction operations
// ---------------------------------------------------------------------------

#[test]
fn test_sum_dim1_parity() {
    let test_name = "test_sum_dim1_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("reduction").join("sum_dim1");
    let input = load_input(&dir);
    let expected = load_expected(&dir, test_name);
    let actual = input.sum_keepdim(1).expect("sum_keepdim should succeed");
    assert_parity(test_name, &actual, &expected, 1e-4);
}

#[test]
fn test_mean_dim1_parity() {
    let test_name = "test_mean_dim1_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("reduction").join("mean_dim1");
    let input = load_input(&dir);
    let expected = load_expected(&dir, test_name);
    let actual = input.mean_keepdim(1).expect("mean_keepdim should succeed");
    assert_parity(test_name, &actual, &expected, 1e-4);
}

#[test]
fn test_max_dim1_parity() {
    let test_name = "test_max_dim1_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("reduction").join("max_dim1");
    let input = load_input(&dir);
    let expected = load_expected(&dir, test_name);
    let actual = input.max_keepdim(1).expect("max_keepdim should succeed");
    assert_parity(test_name, &actual, &expected, 1e-4);
}

// ---------------------------------------------------------------------------
// Shape operations
// ---------------------------------------------------------------------------

#[test]
fn test_transpose_parity() {
    let test_name = "test_transpose_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("shape").join("transpose");
    let input = load_input(&dir);
    let expected = load_expected(&dir, test_name);
    // PyTorch: x.transpose(1, 2) on shape [2, 3, 4]
    let actual = input.transpose(1, 2).expect("transpose should succeed");
    assert_parity(test_name, &actual, &expected, 1e-6);
}

#[test]
fn test_reshape_parity() {
    let test_name = "test_reshape_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("shape").join("reshape");
    let input = load_input(&dir);
    let expected = load_expected(&dir, test_name);
    // PyTorch: x.reshape(6, 4) on shape [2, 3, 4]
    let actual = input.reshape([6, 4]).expect("reshape should succeed");
    assert_parity(test_name, &actual, &expected, 1e-6);
}

#[test]
fn test_cat_parity() {
    let test_name = "test_cat_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("shape").join("cat");
    let a = load_input_n(&dir, 0);
    let b = load_input_n(&dir, 1);
    let expected = load_expected(&dir, test_name);
    // PyTorch: torch.cat([x, y], dim=0)
    let actual = DynTensor::cat(&[&a, &b], 0).expect("cat should succeed");
    assert_parity(test_name, &actual, &expected, 1e-6);
}

// ---------------------------------------------------------------------------
// Normalization (LayerNorm)
// ---------------------------------------------------------------------------

#[test]
fn test_layernorm_parity() {
    let test_name = "test_layernorm_parity";
    if !refs_available(test_name) {
        return;
    }
    let dir = ref_dir().join("norm").join("layernorm");
    let input = load_input(&dir);
    let expected = load_expected(&dir, test_name);

    // Load LayerNorm parameters from metadata.
    let meta_path = dir.join("metadata.json");
    let meta: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(&meta_path).expect("metadata.json should exist"),
    )
    .expect("valid JSON");

    let weight: Vec<f32> = meta["weight"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();
    let bias: Vec<f32> = meta["bias"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();
    let eps = meta["eps"].as_f64().unwrap_or(1e-5);

    let normalized_size = weight.len();
    let weight_t =
        DynTensor::from_vec(weight, vec![normalized_size], &Device::Cpu).expect("weight tensor");
    let bias_t =
        DynTensor::from_vec(bias, vec![normalized_size], &Device::Cpu).expect("bias tensor");

    // Manual layer norm: normalize last dim, then affine.
    let ln = nn_core::LayerNorm::new(weight_t, bias_t, eps).expect("valid LayerNorm");
    let actual = ln
        .forward(&input)
        .expect("layernorm forward should succeed");
    assert_parity(test_name, &actual, &expected, 1e-4);
}
