// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! L3 parity test — PyTorch reference vs nn CompiledKokoro output.
//!
//! Proves that nn's CompiledKokoro produces output matching the PyTorch
//! reference within decomposed acceptance criteria:
//!   - AC1: Informational (end-to-end ~0.15 due to STFT phase wrapping)
//!   - AC2: MCD < 6.0 dB vs PyTorch reference
//!   - AC3: Cosine similarity > 0.85 vs PyTorch reference
//!
//! Per-stage correctness: AC1-D < 1e-3, AC1-S cosine > 0.99, AC1-E < 1e-4.
//!
//! Gated on environment variables:
//!   - `KOKORO_WEIGHTS`: path to kokoro_v1_0.safetensors model weights
//!   - `KOKORO_REFERENCE`: path to kokoro_reference.safetensors (PyTorch output)
//!
//! The reference file must contain `input_ids`, `style`, `speed`, and `audio`
//! tensors, generated by the Python companion script. This ensures the Rust
//! test uses identical model inputs to the PyTorch reference.
//!
//! Generate reference data:
//!   python crates/nn-import/python/kokoro_reference.py \
//!     --weights kokoro_v1_0.safetensors \
//!     --output kokoro_reference.safetensors
//!
//! Run:
//!   KOKORO_WEIGHTS=path/to/kokoro_v1_0.safetensors \
//!   KOKORO_REFERENCE=path/to/kokoro_reference.safetensors \
//!   cargo test -p nn-metal --test kokoro_l3_parity
//!
//! Part of #2466 (L3 parity test).
//! Part of #2218 (Kokoro epic).

use nn_core::dyn_tensor::DynTensor;
use nn_core::Device;
use nn_reftest::{compare_tensors, load_safetensors, ComparisonConfig, NamedTensor};
use nn_tts_verify::quality;

// -- Env-var gating -----------------------------------------------------------

/// Returns (weights_path, reference_path) or None if env vars are missing.
pub(super) fn require_paths() -> Option<(String, String)> {
    super::kokoro_test_env::require_kokoro_weights_and_reference("Kokoro L3 parity not run.")
}

// -- Reference data loading ---------------------------------------------------

/// Load input_ids, style, speed, and reference audio from the reference file.
///
/// The reference safetensors must contain:
///   - `input_ids`: [1, T] phoneme token IDs (saved as F32, used as embedding indices)
///   - `style`: [1, 2*style_dim] voice embedding
///   - `speed`: [1] speed multiplier
///   - `audio`: [1, 1, T_audio] reference PCM waveform
fn load_reference(path: &str) -> (DynTensor, DynTensor, f32, Vec<f32>) {
    let trace = load_safetensors(path).expect("load reference safetensors");

    let ids_tensor = trace
        .get_by_name("input_ids")
        .expect("missing 'input_ids' in reference");
    let style_tensor = trace
        .get_by_name("style")
        .expect("missing 'style' in reference");
    let speed_tensor = trace
        .get_by_name("speed")
        .expect("missing 'speed' in reference");
    let audio_tensor = trace
        .get_by_name("audio")
        .expect("missing 'audio' in reference");

    let input_ids = DynTensor::from_vec(ids_tensor.data.clone(), &ids_tensor.shape, &Device::Cpu)
        .expect("build input_ids DynTensor");

    let style = DynTensor::from_vec(style_tensor.data.clone(), &style_tensor.shape, &Device::Cpu)
        .expect("build style DynTensor");

    let speed = speed_tensor.data[0];

    (input_ids, style, speed, audio_tensor.data.clone())
}

// -- Shared synthesis ---------------------------------------------------------

/// Run CompiledKokoro synthesis and return (nn_audio_f32, ref_audio_data).
/// Both truncated to matching length.
pub(super) fn synthesize_and_load_ref(weights: &str, reference: &str) -> (Vec<f32>, Vec<f32>) {
    super::test_utils::gpu_init();
    let cache = super::test_utils::metal_setup();

    let (input_ids, style, speed, ref_audio) = load_reference(reference);

    // Use Warn policy: test/reference tokens may produce click artifacts with
    // production weights that fail the no_clicks hard bound. Part of #4262.
    let mut hb = nn_tts_verify::HardBoundsConfig::default();
    hb.rejection_policy = nn_tts_verify::RejectionPolicy::Warn;

    // SAFETY: safetensors file not modified while alive.
    let mut kokoro = unsafe {
        nn_metal::compiled_kokoro::CompiledKokoro::load_with_hard_bounds(weights, hb)
            .expect("failed to load Kokoro weights")
    };

    let (audio, cert) = kokoro
        .synthesize(&input_ids, &style, speed, &cache)
        .expect("synthesis failed");

    assert!(
        cert.overall_passed,
        "TTS hard bounds failed: {:?}",
        cert.hard_bounds
            .iter()
            .filter(|b| !b.passed)
            .collect::<Vec<_>>()
    );

    let nn_audio = audio
        .to_device(&Device::Cpu)
        .expect("GPU to CPU")
        .to_flat_vec::<f32>()
        .expect("f32 extract");

    let min_len = nn_audio.len().min(ref_audio.len());
    assert!(min_len > 0, "both outputs must be non-empty");

    eprintln!(
        "Audio lengths: nn={}, ref={}, compared={}",
        nn_audio.len(),
        ref_audio.len(),
        min_len,
    );

    (nn_audio[..min_len].to_vec(), ref_audio[..min_len].to_vec())
}

// -- Tests --------------------------------------------------------------------

/// AC1: end-to-end audio max error (informational, not asserted).
///
/// End-to-end AC1 is ~0.15 due to STFT atan2 phase wrapping — a mathematical
/// discontinuity, not a bug. Per-stage correctness is proven by decomposed
/// metrics (AC1-E, AC1-F, AC1-D, AC2, AC3).
/// See `designs/2026-03-19-kokoro-ac1-decomposed-correctness.md`.
///
/// Part of #2466, #2691.
#[test]
fn test_l3_parity_spectrogram() {
    let (weights, reference) = match require_paths() {
        Some(p) => p,
        None => return,
    };

    let (nn_audio, ref_audio) = synthesize_and_load_ref(&weights, &reference);
    let n = nn_audio.len();

    let nn_named = NamedTensor::new("audio", vec![n], nn_audio).expect("valid");
    let ref_named = NamedTensor::new("audio", vec![n], ref_audio).expect("valid");

    // AC1 is informational — do not assert < 1e-3.
    // Expected: ~0.15 due to STFT atan2 phase wrapping (see design doc).
    // Correctness is proven by per-stage metrics: AC1-D < 1e-3, AC2 < 6dB, AC3 > 0.85.
    let config = ComparisonConfig::new(1.0, 1.0, 0.0);
    let cmp = compare_tensors(&ref_named, &nn_named, &config).expect("compare");

    assert!(!cmp.max_abs_diff.is_nan(), "audio contains NaN values");
    assert!(
        cmp.max_abs_diff.is_finite(),
        "audio max abs error is not finite"
    );
    eprintln!(
        "AC1 (informational): max_abs={:.6e}, cosine={:.6}, n={}",
        cmp.max_abs_diff, cmp.cosine_similarity, n,
    );
}

#[test]
fn test_l3_parity_mcd() {
    let (weights, reference) = match require_paths() {
        Some(p) => p,
        None => return,
    };

    let (nn_audio, ref_audio) = synthesize_and_load_ref(&weights, &reference);

    // AC2: MCD < 6.0 dB (Kubichek 1993).
    let mcd =
        quality::compute_mcd(&nn_audio, &ref_audio, 24000, 6.0).expect("MCD computation failed");

    assert!(
        mcd.passed,
        "AC2 FAILED: MCD={:.2} dB (max {:.1})",
        mcd.value, mcd.threshold
    );
    eprintln!(
        "AC2 PASSED: MCD={:.2} dB (< {:.1})",
        mcd.value, mcd.threshold
    );
}

#[test]
fn test_l3_parity_cosine_similarity() {
    let (weights, reference) = match require_paths() {
        Some(p) => p,
        None => return,
    };

    let (nn_audio, ref_audio) = synthesize_and_load_ref(&weights, &reference);

    // AC3: Cosine similarity > 0.85.
    let cosine = quality::compute_cosine_similarity(&nn_audio, &ref_audio, 0.85)
        .expect("cosine computation failed");

    assert!(
        cosine.passed,
        "AC3 FAILED: cosine={:.4} (min {:.2})",
        cosine.value, cosine.threshold
    );
    eprintln!(
        "AC3 PASSED: cosine={:.4} (> {:.2})",
        cosine.value, cosine.threshold
    );
}
