#![allow(deprecated)]
// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Whisper real-weight parity tests: compare nn Whisper output against
//! PyTorch reference tensors generated by `convert_whisper_safetensors.py`.
//!
//! These tests require pre-generated model weights and reference I/O:
//! ```
//! ```
//!
//! When weights are not available, tests print a message and return early
//! (tests always pass or fail — never skipped via attributes).
//!
//! Part of #1557 — Whisper real-weight parity testing.
//! Part of #3080 — Whisper quality validation (WER gate).

use std::path::Path;

use nn_core::dyn_tensor::DynTensor;
use nn_core::Device;
use nn_reftest::{compare_tensors, ComparisonConfig, NamedTensor};
use nn_whisper::{
    transcribe, whisper_mel_spectrogram_for_config, word_error_rate, DecodeConfig, WhisperConfig,
    WhisperModel, WhisperTokenizer,
};

const WEIGHTS_DIR: &str = "models/whisper";

/// Convert a DynTensor to a NamedTensor for comparison.
fn to_named(tensor: &DynTensor, name: &str) -> NamedTensor {
    let data = tensor.to_flat_vec::<f32>().expect("to_flat_vec_f32");
    let shape = tensor.dims().to_vec();
    NamedTensor::new(name, shape, data).expect("create NamedTensor")
}

/// Load a DynTensor from a safetensors file by key name.
fn load_tensor(path: &Path, key: &str) -> DynTensor {
    let data = std::fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let st = safetensors::SafeTensors::deserialize(&data)
        .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));
    let view = st
        .tensor(key)
        .unwrap_or_else(|e| panic!("key '{}' in {}: {e}", key, path.display()));
    let shape: Vec<usize> = view.shape().to_vec();
    let bytes = view.data();
    let floats: Vec<f32> = bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    DynTensor::new(&floats, &shape, &Device::Cpu).expect("create tensor")
}

/// Check if the whisper model weights are available.
fn weights_available() -> bool {
    let weights_path = Path::new(WEIGHTS_DIR).join("whisper_tiny.safetensors");
    if weights_path.exists() {
        return true;
    }
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(WEIGHTS_DIR);
    repo_root.join("whisper_tiny.safetensors").exists()
}

/// Resolve the weights directory path.
fn resolve_weights_dir() -> std::path::PathBuf {
    let direct = Path::new(WEIGHTS_DIR);
    if direct.join("whisper_tiny.safetensors").exists() {
        return direct.to_path_buf();
    }
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(WEIGHTS_DIR)
}

/// Add batch dimension if needed (safetensors reference may be 2D).
fn ensure_batch_dim(tensor: DynTensor) -> DynTensor {
    if tensor.rank() == 2 {
        tensor.unsqueeze(0).expect("add batch dim")
    } else {
        tensor
    }
}

#[test]
fn test_whisper_tiny_encoder_parity() {
    if !weights_available() {
        eprintln!(
            "Skipping test_whisper_tiny_encoder_parity: run \
        );
        return;
    }

    let dir = resolve_weights_dir();
    let config = WhisperConfig::whisper_tiny();
    let weights_path = dir.join("whisper_tiny.safetensors");
    let mut model =
        WhisperModel::load_safetensors(&weights_path, config.clone()).expect("load whisper-tiny");

    // Load reference mel spectrogram and add batch dim.
    let mel = ensure_batch_dim(load_tensor(
        &dir.join("reference_mel.safetensors"),
        "mel_input",
    ));

    assert_eq!(
        mel.dim(1).unwrap(),
        config.num_mel_bins,
        "mel bins mismatch: got {}, expected {}",
        mel.dim(1).unwrap(),
        config.num_mel_bins,
    );

    let encoder_out = model.encode(&mel).expect("encoder forward");
    let reference = ensure_batch_dim(load_tensor(
        &dir.join("reference_encoder.safetensors"),
        "encoder_output",
    ));

    // Whisper-tiny (4 encoder layers): < 1e-3 absolute tolerance.
    let comparison = ComparisonConfig::new(1e-3, 1e-2, 0.999);
    let enc_named = to_named(&encoder_out, "encoder_output");
    let ref_named = to_named(&reference, "encoder_output_ref");
    compare_tensors(&enc_named, &ref_named, &comparison).unwrap_or_else(|e| {
        let max_abs = enc_named
            .data
            .iter()
            .zip(ref_named.data.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        panic!(
            "Encoder parity failed (max_abs_err={max_abs:.6}): {e}\n\
             encoder_out shape: {:?}, reference shape: {:?}",
            encoder_out.dims(),
            reference.dims(),
        );
    });
}

#[test]
fn test_whisper_tiny_decoder_parity() {
    if !weights_available() {
        eprintln!(
            "Skipping test_whisper_tiny_decoder_parity: run \
        );
        return;
    }

    let dir = resolve_weights_dir();
    let config = WhisperConfig::whisper_tiny();
    let weights_path = dir.join("whisper_tiny.safetensors");
    let mut model =
        WhisperModel::load_safetensors(&weights_path, config).expect("load whisper-tiny");

    // Load reference encoder output to feed to decoder.
    let encoder_output = ensure_batch_dim(load_tensor(
        &dir.join("reference_encoder.safetensors"),
        "encoder_output",
    ));

    // SOT=50258, en=50259, transcribe=50360, notimestamps=50364
    let token_ids: Vec<u32> = vec![50258, 50259, 50360, 50364];
    let tokens = DynTensor::from_vec_u32(token_ids, &[1, 4], &Device::Cpu).expect("create tokens");

    let logits = model
        .decode(&tokens, &encoder_output, true, 0)
        .expect("decoder forward");

    let ref_logits = ensure_batch_dim(load_tensor(
        &dir.join("reference_decoder.safetensors"),
        "decoder_logits",
    ));

    // Decoder logits (4 layers + cross-attention + vocab matmul): looser tolerance.
    let comparison = ComparisonConfig::new(1e-2, 5e-2, 0.99);
    let out_named = to_named(&logits, "decoder_logits");
    let ref_named = to_named(&ref_logits, "decoder_logits_ref");
    compare_tensors(&out_named, &ref_named, &comparison).unwrap_or_else(|e| {
        let max_abs = out_named
            .data
            .iter()
            .zip(ref_named.data.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        panic!(
            "Decoder parity failed (max_abs_err={max_abs:.6}): {e}\n\
             logits shape: {:?}, reference shape: {:?}",
            logits.dims(),
            ref_logits.dims(),
        );
    });
}

#[test]
fn test_whisper_tiny_mel_spectrogram() {
    if !weights_available() {
        eprintln!(
            "Skipping test_whisper_tiny_mel_spectrogram: run \
        );
        return;
    }

    let dir = resolve_weights_dir();

    // Load the reference audio (3s 440 Hz sine at 16kHz).
    let audio_ref = load_tensor(&dir.join("reference_audio.safetensors"), "audio");
    let audio: Vec<f32> = audio_ref.to_flat_vec::<f32>().expect("audio to vec");

    // Pad to 30 seconds (480,000 samples) matching HuggingFace WhisperProcessor
    // which always pads to N_SAMPLES before computing the mel spectrogram.
    let n_samples = 16_000 * 30; // 480,000
    let mut padded_audio = audio;
    padded_audio.resize(n_samples, 0.0);

    // Compute mel spectrogram using nn.
    let config = WhisperConfig::whisper_tiny();
    let mel_raw = whisper_mel_spectrogram_for_config(&padded_audio, config.num_mel_bins)
        .expect("mel spectrogram");

    // Load PyTorch reference mel.
    let mel_ref = ensure_batch_dim(load_tensor(
        &dir.join("reference_mel.safetensors"),
        "mel_input",
    ));

    // Trim nn mel to match reference frame count. Our STFT may produce 1
    // extra frame due to reflect-padding differences (3001 vs 3000 frames).
    let ref_frames = mel_ref.dim(2).unwrap();
    let mel = if mel_raw.dim(2).unwrap() > ref_frames {
        mel_raw.narrow(2, 0, ref_frames).expect("trim mel frames")
    } else {
        mel_raw
    };

    // Mel spectrogram comparison: wider tolerance due to implementation
    // differences (HuggingFace processor vs direct DFT, float precision).
    let comparison = ComparisonConfig::new(0.1, 0.5, 0.95);
    let mel_named = to_named(&mel, "mel");
    let ref_named = to_named(&mel_ref, "mel_ref");
    compare_tensors(&mel_named, &ref_named, &comparison).unwrap_or_else(|e| {
        let max_abs = mel_named
            .data
            .iter()
            .zip(ref_named.data.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        panic!(
            "Mel parity failed (max_abs_err={max_abs:.6}): {e}\n\
             mel shape: {:?}, reference shape: {:?}\n\
             mel range: [{:.4}, {:.4}], ref range: [{:.4}, {:.4}]",
            mel.dims(),
            mel_ref.dims(),
            mel_named.data.iter().copied().fold(f32::INFINITY, f32::min),
            mel_named
                .data
                .iter()
                .copied()
                .fold(f32::NEG_INFINITY, f32::max),
            ref_named.data.iter().copied().fold(f32::INFINITY, f32::min),
            ref_named
                .data
                .iter()
                .copied()
                .fold(f32::NEG_INFINITY, f32::max),
        );
    });
}

#[test]
fn test_whisper_tiny_top1_agreement() {
    if !weights_available() {
        eprintln!(
            "Skipping test_whisper_tiny_top1_agreement: run \
        );
        return;
    }

    let dir = resolve_weights_dir();
    let config = WhisperConfig::whisper_tiny();
    let weights_path = dir.join("whisper_tiny.safetensors");
    let mut model =
        WhisperModel::load_safetensors(&weights_path, config).expect("load whisper-tiny");

    // Load reference encoder output.
    let encoder_output = ensure_batch_dim(load_tensor(
        &dir.join("reference_encoder.safetensors"),
        "encoder_output",
    ));

    // Initial prompt tokens.
    let token_ids: Vec<u32> = vec![50258, 50259, 50360, 50364];
    let tokens = DynTensor::from_vec_u32(token_ids, &[1, 4], &Device::Cpu).expect("create tokens");

    let logits = model
        .decode(&tokens, &encoder_output, true, 0)
        .expect("decoder forward");

    // Load reference logits.
    let ref_logits = ensure_batch_dim(load_tensor(
        &dir.join("reference_decoder.safetensors"),
        "decoder_logits",
    ));

    // Check that top-1 token predictions agree for all 4 positions.
    let nn_flat = logits.to_flat_vec::<f32>().unwrap();
    let ref_flat = ref_logits.to_flat_vec::<f32>().unwrap();

    let vocab_size = logits.dim(2).unwrap();
    let seq_len = logits.dim(1).unwrap();

    for pos in 0..seq_len {
        let nn_start = pos * vocab_size;
        let nn_slice = &nn_flat[nn_start..nn_start + vocab_size];
        let ref_start = pos * vocab_size;
        let ref_slice = &ref_flat[ref_start..ref_start + vocab_size];

        let nn_top1 = nn_slice
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .map(|(i, _)| i)
            .unwrap();
        let ref_top1 = ref_slice
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .map(|(i, _)| i)
            .unwrap();

        assert_eq!(
            nn_top1, ref_top1,
            "Top-1 token mismatch at position {pos}: nn={nn_top1}, ref={ref_top1}",
        );
    }
}

#[test]
fn test_whisper_tiny_config_validates() {
    let config = WhisperConfig::whisper_tiny();
    config
        .validate()
        .expect("whisper_tiny config should be valid");
    assert_eq!(config.num_mel_bins, 80);
    assert_eq!(config.d_model, 384);
    assert_eq!(config.encoder_layers, 4);
    assert_eq!(config.decoder_layers, 4);
    assert_eq!(config.encoder_attention_heads, 6);
    assert_eq!(config.decoder_attention_heads, 6);
    assert_eq!(config.encoder_head_dim(), 64);
    assert_eq!(config.decoder_head_dim(), 64);
}

#[test]
fn test_whisper_tiny_mel_shape() {
    let config = WhisperConfig::whisper_tiny();
    // 3 seconds of audio at 16kHz.
    let audio = vec![0.0f32; 48000];
    let mel =
        whisper_mel_spectrogram_for_config(&audio, config.num_mel_bins).expect("mel spectrogram");
    assert_eq!(mel.dim(0).unwrap(), 1, "batch dim");
    assert_eq!(
        mel.dim(1).unwrap(),
        80,
        "mel bins should be 80 for whisper-tiny"
    );
    assert!(mel.dim(2).unwrap() > 0, "should have at least 1 frame");
}

/// End-to-end transcription test with WER gate.
///
/// Loads whisper-tiny weights, transcribes a reference speech clip, and
/// asserts WER < 0.15 against the known transcript. This is the quality
/// regression gate for Whisper inference correctness.
///
/// Part of #3080.
#[test]
fn test_whisper_tiny_transcribe_wer() {
    if !weights_available() {
        eprintln!(
            "Skipping test_whisper_tiny_transcribe_wer: run \
        );
        return;
    }

    let dir = resolve_weights_dir();

    // Load model.
    let config = WhisperConfig::whisper_tiny();
    let weights_path = dir.join("whisper_tiny.safetensors");
    let mut model =
        WhisperModel::load_safetensors(&weights_path, config.clone()).expect("load whisper-tiny");

    // Load tokenizer.
    let vocab_path = dir.join("vocab.json");
    let merges_path = dir.join("merges.txt");
    let vocab_json =
        std::fs::read_to_string(&vocab_path).unwrap_or_else(|e| panic!("read vocab.json: {e}"));
    let merges_text =
        std::fs::read_to_string(&merges_path).unwrap_or_else(|e| panic!("read merges.txt: {e}"));
    let tokenizer =
        WhisperTokenizer::from_vocab_and_merges(&vocab_json, &merges_text).expect("load tokenizer");

    // Load reference speech audio.
    let speech_tensor = load_tensor(&dir.join("reference_speech.safetensors"), "audio");
    let audio: Vec<f32> = speech_tensor.to_flat_vec::<f32>().expect("audio to vec");

    // Load reference transcript.
    let transcript_path = dir.join("reference_transcript.txt");
    let reference = std::fs::read_to_string(&transcript_path)
        .unwrap_or_else(|e| panic!("read reference_transcript.txt: {e}"))
        .trim()
        .to_string();

    // Compute mel spectrogram (pad to 30s as Whisper expects).
    let n_samples = 16_000 * 30;
    let mut padded = audio;
    padded.resize(n_samples, 0.0);
    let mel =
        whisper_mel_spectrogram_for_config(&padded, config.num_mel_bins).expect("mel spectrogram");

    // Encode audio.
    let encoder_output = model.encode(&mel).expect("encode");

    // Transcribe.
    let decode_config = DecodeConfig::default();
    let result =
        transcribe(&mut model, &encoder_output, &decode_config, &tokenizer).expect("transcribe");

    let hypothesis = result.text.trim().to_string();
    let wer = word_error_rate(&hypothesis, &reference);

    eprintln!("Reference:  {reference}");
    eprintln!("Hypothesis: {hypothesis}");
    eprintln!("WER:        {wer:.4}");

    assert!(
        wer < 0.15,
        "WER gate failed: {wer:.4} >= 0.15\n\
         Reference:  {reference}\n\
         Hypothesis: {hypothesis}"
    );
}
