// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! End-to-end HTDemucs test with real weights.
//!
//! Loads real model weights from `models/demucs/htdemucs_temporal.safetensors`
//! and runs the full temporal branch forward pass.
//!
//! When weights are absent the test prints a skip message and returns Ok
//! (graceful skip via early return, not test-level skip attributes).
//!
//! Part of #779 — Milestone 1, AC3 (E2E test with real weights).

use std::path::Path;

use nn_metal::{HTDemucs, HTDemucsWeights, MetalBackend, PipelineCache, WeightMap};
use nn_reftest::{compare_tensors, ComparisonConfig, NamedTensor};

/// Project root (two levels up from `crates/nn-metal/`).
fn project_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("project root")
        .to_path_buf()
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Load model from safetensors weights, returning `None` if weights absent.
fn load_model(audio_t: usize) -> Option<(HTDemucs, PipelineCache)> {
    let weights_path = project_root().join("models/demucs/htdemucs_temporal.safetensors");
    if !weights_path.exists() {
        eprintln!(
            "SKIP: Demucs weights not found at {}",
            weights_path.display()
        );
        return None;
    }

    let backend = MetalBackend::init().expect("Metal backend required");
    let ctx = backend.context().clone();

    // SAFETY: weight file is a valid safetensors file, context is initialized,
    // file outlives the WeightMap (dropped in this scope).
    let wm = unsafe { WeightMap::load(&weights_path, &ctx).expect("load safetensors") };
    assert!(
        wm.tensor_count() >= 280,
        "expected >=280 tensors in temporal branch, got {}",
        wm.tensor_count(),
    );

    let weights = HTDemucsWeights::from_weight_map(&wm).expect("weight loading");
    let model = HTDemucs::new(weights, audio_t).expect("model construction");
    let cache = PipelineCache::new(ctx);
    Some((model, cache))
}

/// Assert output is the expected length and all finite.
fn assert_output_valid(out: &[f32], expected_len: usize, label: &str) {
    assert_eq!(out.len(), expected_len, "{label}: length mismatch");
    let non_finite = out.iter().filter(|v| !v.is_finite()).count();
    assert_eq!(non_finite, 0, "{label}: {non_finite} non-finite values");
    eprintln!(
        "{label}: len={}, range=[{:.6}, {:.6}]",
        out.len(),
        out.iter().copied().reduce(f32::min).unwrap_or(0.0),
        out.iter().copied().reduce(f32::max).unwrap_or(0.0),
    );
}

/// Generate deterministic pseudo-random noise of given length.
fn deterministic_noise(len: usize) -> Vec<f32> {
    let mut buf = vec![0.0f32; len];
    let mut rng_state: u64 = 42;
    for v in &mut buf {
        rng_state ^= rng_state << 13;
        rng_state ^= rng_state >> 7;
        rng_state ^= rng_state << 17;
        *v = ((rng_state as f32) / (u64::MAX as f32)) * 0.2 - 0.1;
    }
    buf
}

// ---------------------------------------------------------------------------
// E2E tests
// ---------------------------------------------------------------------------

/// Full e2e test: load real weights → construct HTDemucs → forward pass → verify output.
#[test]
fn e2e_demucs_real_weights() {
    let audio_t: usize = 1024;
    let (model, cache) = match load_model(audio_t) {
        Some(pair) => pair,
        None => return,
    };

    let expected_len = 8 * audio_t;

    // Forward pass with silence.
    let silence = vec![0.0f32; 2 * audio_t];
    let out = model.forward(&cache, &silence).expect("forward (silence)");
    assert_output_valid(&out, expected_len, "silence");

    // Forward pass with deterministic noise.
    let noise = deterministic_noise(2 * audio_t);
    let out_noise = model.forward(&cache, &noise).expect("forward (noise)");
    assert_output_valid(&out_noise, expected_len, "noise");

    eprintln!("HTDemucs e2e: PASS (silence + noise, {expected_len} output samples)");
}

/// Load f32 binary file as Vec<f32>. Returns None if file not found.
fn load_f32_bin(path: &Path) -> Option<Vec<f32>> {
    if !path.exists() {
        return None;
    }
    let bytes = std::fs::read(path).expect("read binary file");
    assert_eq!(bytes.len() % 4, 0, "file size not aligned to f32");
    Some(
        bytes
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect(),
    )
}

/// PyTorch parity test: compare nn output against Python reference.
///
/// The reference is generated by:
///
/// The Python script reconstructs the temporal-only forward pass using
/// PyTorch ops with real weights, matching Rust behavior:
/// - Mono mean/std normalization
/// - Zero spectral branch
/// - No Q/K/V/out attention biases
///
/// Part of #779 — Milestone 1, AC4 (PyTorch parity test).
#[test]
fn e2e_demucs_pytorch_parity() {
    let audio_t: usize = 1024;
    let root = project_root();

    // Load reference input/output files.
    let audio_path = root.join(format!("models/demucs/parity_audio_{audio_t}.bin"));
    let ref_path = root.join(format!("models/demucs/parity_output_{audio_t}.bin"));

    let audio = match load_f32_bin(&audio_path) {
        Some(a) => a,
        None => {
            eprintln!(
                "SKIP: Parity reference not found at {}",
                audio_path.display()
            );
            return;
        }
    };
    let expected = load_f32_bin(&ref_path).expect("parity output missing");

    assert_eq!(audio.len(), 2 * audio_t, "audio length");
    assert_eq!(expected.len(), 8 * audio_t, "expected output length");

    // Run nn forward pass.
    let (model, cache) = match load_model(audio_t) {
        Some(pair) => pair,
        None => return,
    };
    let actual = model.forward(&cache, &audio).expect("forward pass");
    assert_eq!(actual.len(), expected.len(), "output length mismatch");

    // Compare via nn-reftest with GPU-appropriate tolerances.
    // GPU float32 dispatch may differ from CPU PyTorch due to op ordering,
    // fused multiply-add, and Metal FTZ behavior. Use atol=1e-3, rtol=1e-2.
    let shape = vec![actual.len()];
    let reference = NamedTensor::new("pytorch_output", shape.clone(), expected)
        .expect("valid reference tensor");
    let candidate = NamedTensor::new("nn_output", shape, actual).expect("valid candidate tensor");
    let config = ComparisonConfig::new(1e-3, 1e-2, 0.999);
    let result = compare_tensors(&reference, &candidate, &config).expect("comparison");
    eprintln!("{result}");
    assert!(
        result.passed,
        "PyTorch parity failed: max_abs={:.6}, max_rel={:.4}, cos={:.6}",
        result.max_abs_diff, result.max_rel_diff, result.cosine_similarity,
    );
    eprintln!("HTDemucs PyTorch parity: PASS");
}

/// Stage comparison: compare encoder and transformer output against Python reference.
///
/// Requires intermediate files saved by `demucs_parity_reference.py -v`:
///   models/demucs/parity_encoder_1024.bin   — encoder bottleneck [384, 4]
///   models/demucs/parity_transformer_1024.bin — transformer output [384, 4]
#[test]
fn e2e_demucs_stage_comparison() {
    let audio_t: usize = 1024;
    let root = project_root();

    let audio_path = root.join(format!("models/demucs/parity_audio_{audio_t}.bin"));
    let audio = match load_f32_bin(&audio_path) {
        Some(a) => a,
        None => {
            eprintln!("SKIP: parity audio not found");
            return;
        }
    };

    let (model, cache) = match load_model(audio_t) {
        Some(pair) => pair,
        None => return,
    };

    let (enc_bottleneck, xformer_out, _final) =
        model.forward_debug(&cache, &audio).expect("forward_debug");

    // Compare encoder bottleneck via nn-reftest.
    let abs_only_config = ComparisonConfig::new(1e-3, f32::INFINITY, 0.0);
    if let Some(ref_enc) =
        load_f32_bin(&root.join(format!("models/demucs/parity_encoder_{audio_t}.bin")))
    {
        let reference = NamedTensor::new("encoder_ref", vec![ref_enc.len()], ref_enc)
            .expect("valid encoder reference");
        let candidate = NamedTensor::new("encoder_nn", vec![enc_bottleneck.len()], enc_bottleneck)
            .expect("valid encoder candidate");
        let result =
            compare_tensors(&reference, &candidate, &abs_only_config).expect("encoder comparison");
        eprintln!("{result}");
        assert!(
            result.passed,
            "Encoder bottleneck parity failed: max_abs={:.6}",
            result.max_abs_diff,
        );
    } else {
        eprintln!("SKIP: encoder reference not found");
    }

    // Compare transformer output via nn-reftest.
    if let Some(ref_xf) =
        load_f32_bin(&root.join(format!("models/demucs/parity_transformer_{audio_t}.bin")))
    {
        let reference = NamedTensor::new("transformer_ref", vec![ref_xf.len()], ref_xf)
            .expect("valid transformer reference");
        let candidate = NamedTensor::new("transformer_nn", vec![xformer_out.len()], xformer_out)
            .expect("valid transformer candidate");
        let result = compare_tensors(&reference, &candidate, &abs_only_config)
            .expect("transformer comparison");
        eprintln!("{result}");
        assert!(
            result.passed,
            "Transformer parity failed: max_abs={:.6}",
            result.max_abs_diff,
        );
    } else {
        eprintln!("SKIP: transformer reference not found");
    }
}

/// Test that weight loading produces correct tensor counts.
#[test]
fn e2e_demucs_weight_loading() {
    let weights_path = project_root().join("models/demucs/htdemucs_temporal.safetensors");
    if !weights_path.exists() {
        eprintln!("SKIP: Demucs weights not found");
        return;
    }

    let backend = MetalBackend::init().expect("Metal backend required");
    let ctx = backend.context().clone();
    let wm = unsafe { WeightMap::load(&weights_path, &ctx).expect("load safetensors") };
    let weights = HTDemucsWeights::from_weight_map(&wm).expect("weight loading");

    assert_eq!(weights.encoder.blocks.len(), 4, "encoder block count");
    for (i, block) in weights.encoder.blocks.iter().enumerate() {
        assert_eq!(block.dconv.len(), 2, "encoder block {i}: DConv sub-layers");
    }

    assert_eq!(weights.decoder.blocks.len(), 4, "decoder block count");
    for (i, block) in weights.decoder.blocks.iter().enumerate() {
        assert_eq!(block.dconv.len(), 2, "decoder block {i}: DConv sub-layers");
    }

    assert_eq!(
        weights.transformer.temporal_layers.len(),
        5,
        "temporal layers"
    );
    assert_eq!(
        weights.transformer.spectral_layers.len(),
        5,
        "spectral layers"
    );
    eprintln!("HTDemucs weight loading: PASS (4 enc + 5 xformer + 4 dec)");
}

/// Compare two f32 slices using nn-reftest `compare_tensors()`.
///
/// Uses absolute tolerance 1e-3 with relative and cosine gates disabled.
/// Returns `(max_abs_diff, passed)`.
fn compare_parity(rust_data: &[f32], ref_data: &[f32], label: &str) -> (f32, bool) {
    assert_eq!(rust_data.len(), ref_data.len(), "{label}: length mismatch");
    let shape = vec![rust_data.len()];
    let reference = NamedTensor::new(format!("{label}_ref"), shape.clone(), ref_data.to_vec())
        .expect("valid reference tensor");
    let candidate = NamedTensor::new(format!("{label}_nn"), shape, rust_data.to_vec())
        .expect("valid candidate tensor");
    let config = ComparisonConfig::new(1e-3, f32::INFINITY, 0.0);
    let result = compare_tensors(&reference, &candidate, &config).expect("comparison");
    eprintln!("{result}");
    (result.max_abs_diff, result.passed)
}

/// Per-block encoder comparison: isolate which encoder block diverges from Python.
///
/// Requires per-block intermediate files saved by `demucs_parity_reference.py`:
///   models/demucs/parity_enc_block{0..3}_in_{audio_t}.bin
///   models/demucs/parity_enc_block{0..3}_out_{audio_t}.bin
///
/// Part of #779 — parity debugging.
#[test]
fn e2e_demucs_encoder_per_block() {
    let audio_t: usize = 1024;
    let root = project_root();

    let audio_path = root.join(format!("models/demucs/parity_audio_{audio_t}.bin"));
    let audio = match load_f32_bin(&audio_path) {
        Some(a) => a,
        None => {
            eprintln!("SKIP: parity audio not found");
            return;
        }
    };

    let (model, cache) = match load_model(audio_t) {
        Some(pair) => pair,
        None => return,
    };

    let (normalized, block_inputs, block_outputs) = model
        .forward_encoder_debug(&cache, &audio)
        .expect("forward_encoder_debug");

    // Compare normalized audio against Python block0 input.
    let norm_ref_path = root.join(format!("models/demucs/parity_enc_block0_in_{audio_t}.bin"));
    if let Some(ref_block0_in) = load_f32_bin(&norm_ref_path) {
        compare_parity(&normalized, &ref_block0_in, "normalization");
    } else {
        eprintln!("SKIP: block0 input reference not found");
    }

    // Compare each encoder block input and output.
    for b in 0..4 {
        let in_path = root.join(format!(
            "models/demucs/parity_enc_block{b}_in_{audio_t}.bin"
        ));
        if let Some(ref_in) = load_f32_bin(&in_path) {
            compare_parity(&block_inputs[b], &ref_in, &format!("block{b}_in"));
        }

        let out_path = root.join(format!(
            "models/demucs/parity_enc_block{b}_out_{audio_t}.bin"
        ));
        if let Some(ref_out) = load_f32_bin(&out_path) {
            compare_parity(&block_outputs[b], &ref_out, &format!("block{b}_out"));
        } else {
            eprintln!("SKIP: block{b} output reference not found");
        }
    }
    eprintln!("Per-block encoder comparison: DONE (check output for divergence)");
}
