// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Build-time model manifest validation.
//!
//! This module includes the auto-generated const assertions produced by
//! `build.rs` from the TOML configs in `configs/`. The assertions validate:
//!
//! - Layer dimension chaining: `output_dim[i] == input_dim[i+1]`
//! - Attention head divisibility: `input_dim % num_heads == 0`
//! - Positive dimensions and ranks
//! - Dtype consistency across layers
//! - Weight naming convention constraints
//!
//! If any assertion fails, the build fails with a descriptive message
//! identifying the model and the offending layers.

#[allow(clippy::manual_is_multiple_of)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/model_checks.rs"));
}

#[cfg(test)]
mod tests {
    use super::generated::*;
    #[allow(unused_imports, unused_qualifications)]
    use super::*;

    // -- Granite-Docling-258M checks ------------------------------------------

    #[test]
    fn test_granite_docling_constants_are_populated() {
        // These consts are generated by build.rs from
        // configs/granite_docling_258m.toml.
        assert_eq!(GRANITE_DOCLING_258M_INPUT_RANK, 4);
        assert_eq!(GRANITE_DOCLING_258M_OUTPUT_RANK, 3);
        assert!(GRANITE_DOCLING_258M_PARAM_COUNT_BOUND > 0);
        assert_eq!(GRANITE_DOCLING_258M_LAYER_COUNT, 6);
    }

    #[test]
    fn test_granite_docling_layer_dims() {
        // Vision encoder: patch_embed outputs 768.
        assert_eq!(
            GRANITE_DOCLING_258M_LAYER0_VISION_PATCH_EMBED_OUTPUT_DIM,
            768
        );
        // Vision encoder: encoder takes 768.
        assert_eq!(GRANITE_DOCLING_258M_LAYER1_VISION_ENCODER_INPUT_DIM, 768);
        // Language model: lm_head outputs vocab_size.
        assert_eq!(
            GRANITE_DOCLING_258M_LAYER5_LANGUAGE_LM_HEAD_OUTPUT_DIM,
            49152
        );
    }

    #[test]
    fn test_granite_docling_weight_prefixes() {
        assert_eq!(GRANITE_DOCLING_258M_WEIGHT_PREFIX_COUNT, 6);
        assert_eq!(GRANITE_DOCLING_258M_WEIGHT_PREFIXES.len(), 6);
        assert!(GRANITE_DOCLING_258M_WEIGHT_PREFIXES[0].starts_with("vision_model"));
    }

    #[test]
    fn test_granite_docling_cross_chain_vision_to_language() {
        // Cross-chain constraint: vision output dim == language encoder input dim.
        assert_eq!(
            GRANITE_DOCLING_258M_LAYER2_VISION_POST_LAYERNORM_OUTPUT_DIM,
            GRANITE_DOCLING_258M_LAYER4_LANGUAGE_ENCODER_INPUT_DIM,
        );
    }

    #[test]
    fn test_granite_docling_attention_head_divisibility() {
        // Vision encoder: 768 / 12 = 64.
        assert_eq!(
            GRANITE_DOCLING_258M_LAYER1_VISION_ENCODER_INPUT_DIM
                % GRANITE_DOCLING_258M_LAYER1_VISION_ENCODER_NUM_HEADS,
            0
        );
        // Language encoder: 768 / 12 = 64.
        assert_eq!(
            GRANITE_DOCLING_258M_LAYER4_LANGUAGE_ENCODER_INPUT_DIM
                % GRANITE_DOCLING_258M_LAYER4_LANGUAGE_ENCODER_NUM_HEADS,
            0
        );
    }
}
