// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Element-wise (1D) dispatch methods for [`KernelPipeline`].

use super::{checked_output_bytes, KernelPipeline};
use crate::buffer::MetalBuffer;
use crate::context::MetalContext;
use crate::dispatch::BatchEncoder;
use crate::dispatch_plan::threadgroup_width_1d;
use crate::element::MetalElement;
use crate::error::MetalError;

impl KernelPipeline {
    /// Dispatch an element-wise kernel with typed inputs.
    ///
    /// Each slice in `inputs` corresponds to one kernel parameter (in order).
    /// All slices must have the same length. Returns the GPU output as `Vec<E>`.
    ///
    /// Buffer binding layout matches the MSL generated by `emit_msl`:
    /// - `buffer(0)` … `buffer(N-1)`: input parameters
    /// - `buffer(N)`: output buffer
    /// - `buffer(N+1)`: element count (`uint`)
    ///
    /// Supports `f32` and [`half::f16`] via the [`MetalElement`] trait.
    ///
    /// Lazy batch (#2009): encodes into the thread-local lazy batch.
    /// `read_buffer` calls `flush()` before CPU readback.
    #[must_use = "returns a Result that may contain an error"]
    pub fn dispatch_elementwise<E: MetalElement>(
        &self,
        ctx: &MetalContext,
        inputs: &[&[E]],
    ) -> Result<Vec<E>, MetalError> {
        let total = self.validate_inputs(inputs)?;
        if total == 0 {
            return Ok(Vec::new());
        }

        let mut buffers = Vec::with_capacity(inputs.len());
        for input in inputs {
            buffers.push(E::create_buffer(ctx, input)?);
        }

        let out_bytes = checked_output_bytes(total, E::element_size())?;
        let (out_buf, out_offset) = crate::arena::arena_alloc_or_create(ctx, out_bytes)?;
        let total_u32 = self.total_u32(total)?;

        // Lazy batch (#2009): encode into the thread-local lazy batch.
        crate::gpu_scope::get_or_create_batch()
            .map_err(|e| MetalError::DispatchFailed(e.to_string()))?;
        let scope_result =
            crate::gpu_scope::encode_into_lazy_batch(|batch| -> Result<(), MetalError> {
                let encoder = batch.new_encoder()?;
                self.encode_batch_dispatch(&encoder, &buffers, &out_buf, out_offset, total_u32)?;
                encoder.end_encoding();
                Ok(())
            });
        match scope_result {
            Ok(inner) => inner?,
            Err(e) => return Err(MetalError::DispatchFailed(e.to_string())),
        }

        // read_buffer_at_offset calls flush() before CPU readback.
        E::read_buffer_at_offset(&out_buf, out_offset, total)
    }

    /// Dispatch multiple typed launches in one command buffer commit.
    ///
    /// Each entry in `launches` represents one kernel invocation with the same
    /// parameter layout as [`dispatch_elementwise`]. Returns outputs in launch
    /// order.
    ///
    /// Supports `f32` and [`half::f16`] via the [`MetalElement`] trait.
    ///
    /// Lazy batch (#2009): all launches encode into the thread-local lazy batch.
    /// `flush()` is called before CPU readback.
    #[must_use = "returns a Result that may contain an error"]
    pub fn dispatch_elementwise_batch<E: MetalElement>(
        &self,
        ctx: &MetalContext,
        launches: &[&[&[E]]],
    ) -> Result<Vec<Vec<E>>, MetalError> {
        if launches.is_empty() {
            return Ok(Vec::new());
        }

        // (buffer, byte_offset, element_count) per launch; None for empty launches.
        let mut outputs: Vec<Option<(MetalBuffer, usize, usize)>> =
            Vec::with_capacity(launches.len());
        // Kept alive until flush() — Metal buffers must outlive encoding.
        #[allow(clippy::collection_is_never_read)]
        let mut retained_inputs: Vec<Vec<MetalBuffer>> = Vec::with_capacity(launches.len());

        // Lazy batch (#2009): encode all launches into the thread-local lazy batch.
        crate::gpu_scope::get_or_create_batch()
            .map_err(|e| MetalError::DispatchFailed(e.to_string()))?;

        for inputs in launches {
            let total = self.validate_inputs(inputs)?;
            if total == 0 {
                outputs.push(None);
                continue;
            }

            let mut buffers = Vec::with_capacity(inputs.len());
            for input in *inputs {
                buffers.push(E::create_buffer(ctx, input)?);
            }

            let out_bytes = checked_output_bytes(total, E::element_size())?;
            let (out_buf, out_offset) = crate::arena::arena_alloc_or_create(ctx, out_bytes)?;
            let total_u32 = self.total_u32(total)?;

            let scope_result =
                crate::gpu_scope::encode_into_lazy_batch(|batch| -> Result<(), MetalError> {
                    let encoder = batch.new_encoder()?;
                    self.encode_batch_dispatch(
                        &encoder, &buffers, &out_buf, out_offset, total_u32,
                    )?;
                    encoder.end_encoding();
                    Ok(())
                });
            match scope_result {
                Ok(inner) => inner?,
                Err(e) => return Err(MetalError::DispatchFailed(e.to_string())),
            }

            retained_inputs.push(buffers);
            outputs.push(Some((out_buf, out_offset, total)));
        }

        // Lazy batch (#2009): flush before CPU readback.
        crate::gpu_scope::flush().map_err(|e| MetalError::DispatchFailed(e.to_string()))?;

        let mut decoded = Vec::with_capacity(outputs.len());
        for maybe_output in &outputs {
            let values = match maybe_output {
                None => Vec::new(),
                Some((buffer, offset, count)) => E::read_buffer_at_offset(buffer, *offset, *count)?,
            };
            decoded.push(values);
        }

        Ok(decoded)
    }

    fn encode_batch_dispatch(
        &self,
        encoder: &BatchEncoder,
        buffers: &[MetalBuffer],
        out_buf: &MetalBuffer,
        out_offset: usize,
        total: u32,
    ) -> Result<(), MetalError> {
        for (index, buffer) in buffers.iter().enumerate() {
            encoder.set_buffer(index, buffer);
        }
        encoder.set_buffer_with_offset(self.param_count, out_buf, out_offset);
        encoder.set_bytes(self.param_count + 1, &total);

        let threadgroup_size = [threadgroup_width_1d(total), 1, 1];
        let grid_size = [total, 1, 1];
        encoder.encode(&self.pipeline, grid_size, threadgroup_size)
    }
}
