// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Build script for nn-models.
//!
//! Two responsibilities:
//! 1. Link espeak-ng when the `espeak` feature is enabled.
//! 2. Read model configuration TOML files from `configs/` and generate
//!    Rust const assertions that validate layer dimension chaining,
//!    weight naming conventions, and dtype consistency at compile time.

use serde::Deserialize;
use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    // --- espeak-ng linking (feature-gated) ---
    if std::env::var("CARGO_FEATURE_ESPEAK").is_ok() {
        if try_pkg_config().is_err() {
            println!("cargo:rustc-link-search=native=/opt/homebrew/lib");
            println!("cargo:rustc-link-lib=dylib=espeak-ng");
        }
    }

    // --- Model manifest validation code generation ---
    generate_model_checks();
}

fn try_pkg_config() -> Result<(), ()> {
    let output = std::process::Command::new("pkg-config")
        .args(["--libs", "espeak-ng"])
        .output()
        .map_err(|_| ())?;

    if !output.status.success() {
        return Err(());
    }

    let flags = String::from_utf8_lossy(&output.stdout);
    for flag in flags.split_whitespace() {
        if let Some(path) = flag.strip_prefix("-L") {
            println!("cargo:rustc-link-search=native={path}");
        } else if let Some(lib) = flag.strip_prefix("-l") {
            println!("cargo:rustc-link-lib=dylib={lib}");
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Model config TOML schema
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct ModelConfig {
    model: ModelMeta,
    #[serde(default)]
    layers: Vec<LayerDef>,
    #[serde(default)]
    cross_chain_constraints: Vec<CrossChainConstraint>,
    #[serde(default)]
    weight_convention: Option<WeightConvention>,
}

#[derive(Deserialize)]
struct ModelMeta {
    name: String,
    input_rank: usize,
    output_rank: usize,
    param_count_bound: usize,
}

#[derive(Deserialize)]
struct LayerDef {
    name: String,
    #[serde(default)]
    chain: Option<String>,
    input_dim: usize,
    output_dim: usize,
    dtype: String,
    #[serde(default)]
    num_heads: Option<usize>,
}

#[derive(Deserialize)]
struct CrossChainConstraint {
    from_layer: String,
    to_layer: String,
    #[serde(default)]
    description: Option<String>,
}

#[derive(Deserialize)]
struct WeightConvention {
    separator: String,
    prefixes: Vec<String>,
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

fn generate_model_checks() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let configs_dir = Path::new("configs");

    // Re-run if any config file changes.
    println!("cargo:rerun-if-changed=configs");

    let mut code = String::new();
    writeln!(code, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(code, "// Model manifest compile-time validation.").unwrap();
    writeln!(code).unwrap();

    if configs_dir.is_dir() {
        let mut entries: Vec<_> = fs::read_dir(configs_dir)
            .expect("failed to read configs/")
            .filter_map(Result::ok)
            .filter(|e| e.path().extension().is_some_and(|ext| ext == "toml"))
            .collect();

        // Sort for deterministic output.
        entries.sort_by_key(fs::DirEntry::file_name);

        for entry in &entries {
            let path = entry.path();
            println!("cargo:rerun-if-changed={}", path.display());

            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));

            let config: ModelConfig = toml::from_str(&content)
                .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()));

            generate_checks_for_model(&mut code, &config);
        }
    }

    let out_path = Path::new(&out_dir).join("model_checks.rs");
    let mut file = fs::File::create(&out_path).expect("failed to create model_checks.rs");
    file.write_all(code.as_bytes())
        .expect("failed to write model_checks.rs");
}

fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_uppercase()
}

fn generate_checks_for_model(code: &mut String, config: &ModelConfig) {
    let model_id = sanitize_ident(&config.model.name);

    writeln!(code, "// ---- {name} ----", name = config.model.name).unwrap();
    writeln!(code).unwrap();

    // Model-level const declarations.
    writeln!(
        code,
        "pub(super) const {model_id}_INPUT_RANK: usize = {rank};",
        rank = config.model.input_rank
    )
    .unwrap();
    writeln!(
        code,
        "pub(super) const {model_id}_OUTPUT_RANK: usize = {rank};",
        rank = config.model.output_rank
    )
    .unwrap();
    writeln!(
        code,
        "pub(super) const {model_id}_PARAM_COUNT_BOUND: usize = {bound};",
        bound = config.model.param_count_bound
    )
    .unwrap();
    writeln!(
        code,
        "pub(super) const {model_id}_LAYER_COUNT: usize = {count};",
        count = config.layers.len()
    )
    .unwrap();
    writeln!(code).unwrap();

    // Positive rank/bound assertions.
    writeln!(
        code,
        "const _: () = assert!(\
         {model_id}_INPUT_RANK > 0, \
         \"{name}: input_rank must be > 0\");",
        name = config.model.name
    )
    .unwrap();
    writeln!(
        code,
        "const _: () = assert!(\
         {model_id}_OUTPUT_RANK > 0, \
         \"{name}: output_rank must be > 0\");",
        name = config.model.name
    )
    .unwrap();
    writeln!(
        code,
        "const _: () = assert!(\
         {model_id}_PARAM_COUNT_BOUND > 0, \
         \"{name}: param_count_bound must be > 0\");",
        name = config.model.name
    )
    .unwrap();
    writeln!(code).unwrap();

    // Per-layer const declarations and dimension-positive assertions.
    for (i, layer) in config.layers.iter().enumerate() {
        let layer_id = sanitize_ident(&layer.name);
        writeln!(
            code,
            "pub(super) const {model_id}_LAYER{i}_{layer_id}_INPUT_DIM: usize = {dim};",
            dim = layer.input_dim
        )
        .unwrap();
        writeln!(
            code,
            "pub(super) const {model_id}_LAYER{i}_{layer_id}_OUTPUT_DIM: usize = {dim};",
            dim = layer.output_dim
        )
        .unwrap();

        writeln!(
            code,
            "const _: () = assert!(\
             {model_id}_LAYER{i}_{layer_id}_INPUT_DIM > 0, \
             \"{name}.{lname}: input_dim must be > 0\");",
            name = config.model.name,
            lname = layer.name
        )
        .unwrap();
        writeln!(
            code,
            "const _: () = assert!(\
             {model_id}_LAYER{i}_{layer_id}_OUTPUT_DIM > 0, \
             \"{name}.{lname}: output_dim must be > 0\");",
            name = config.model.name,
            lname = layer.name
        )
        .unwrap();

        // num_heads divisibility check.
        if let Some(num_heads) = layer.num_heads {
            let heads_const = format!("{model_id}_LAYER{i}_{layer_id}_NUM_HEADS");
            writeln!(code, "pub(super) const {heads_const}: usize = {num_heads};").unwrap();
            writeln!(
                code,
                "const _: () = assert!(\
                 {model_id}_LAYER{i}_{layer_id}_INPUT_DIM \
                 % {heads_const} == 0, \
                 \"{name}.{lname}: input_dim must be divisible \
                 by num_heads\");",
                name = config.model.name,
                lname = layer.name
            )
            .unwrap();
        }

        writeln!(code).unwrap();
    }

    // Layer chaining: output_dim[i] == input_dim[i+1] WITHIN each chain.
    let mut chains: BTreeMap<String, Vec<(usize, &LayerDef)>> = BTreeMap::new();
    for (i, layer) in config.layers.iter().enumerate() {
        let chain_name = layer.chain.clone().unwrap_or_else(|| "default".to_string());
        chains.entry(chain_name).or_default().push((i, layer));
    }

    for (chain_name, layers) in &chains {
        if layers.len() < 2 {
            continue;
        }
        writeln!(
            code,
            "// Chain \"{chain_name}\": sequential dimension chaining"
        )
        .unwrap();
        for window in layers.windows(2) {
            let (i, cur) = &window[0];
            let (j, next) = &window[1];
            let cur_id = sanitize_ident(&cur.name);
            let next_id = sanitize_ident(&next.name);

            writeln!(
                code,
                "const _: () = assert!(\
                 {model_id}_LAYER{i}_{cur_id}_OUTPUT_DIM == \
                 {model_id}_LAYER{j}_{next_id}_INPUT_DIM, \
                 \"{name}: {cur_name}.output_dim must equal \
                 {next_name}.input_dim\");",
                name = config.model.name,
                cur_name = cur.name,
                next_name = next.name
            )
            .unwrap();
        }
        writeln!(code).unwrap();
    }

    // Cross-chain constraints.
    if !config.cross_chain_constraints.is_empty() {
        writeln!(code, "// Cross-chain constraints").unwrap();

        // Build name -> (index, layer) lookup.
        let layer_index: BTreeMap<&str, (usize, &LayerDef)> = config
            .layers
            .iter()
            .enumerate()
            .map(|(i, l)| (l.name.as_str(), (i, l)))
            .collect();

        for constraint in &config.cross_chain_constraints {
            let (from_i, from_layer) = layer_index
                .get(constraint.from_layer.as_str())
                .unwrap_or_else(|| {
                    panic!(
                        "cross_chain_constraint from_layer '{}' not found",
                        constraint.from_layer
                    )
                });
            let (to_i, to_layer) = layer_index
                .get(constraint.to_layer.as_str())
                .unwrap_or_else(|| {
                    panic!(
                        "cross_chain_constraint to_layer '{}' not found",
                        constraint.to_layer
                    )
                });

            let from_id = sanitize_ident(&from_layer.name);
            let to_id = sanitize_ident(&to_layer.name);
            let desc = constraint
                .description
                .as_deref()
                .unwrap_or("cross-chain dimension constraint");

            writeln!(
                code,
                "const _: () = assert!(\
                 {model_id}_LAYER{from_i}_{from_id}_OUTPUT_DIM == \
                 {model_id}_LAYER{to_i}_{to_id}_INPUT_DIM, \
                 \"{name}: {desc}\");",
                name = config.model.name,
            )
            .unwrap();
        }
        writeln!(code).unwrap();
    }

    // Dtype consistency check: all layers must use the same dtype.
    if config.layers.len() >= 2 {
        let first_dtype = &config.layers[0].dtype;
        for (i, layer) in config.layers.iter().enumerate().skip(1) {
            if layer.dtype != *first_dtype {
                writeln!(
                    code,
                    "const _: () = assert!(false, \
                     \"{name}: dtype mismatch — \
                     {first}.dtype={fd} vs {cur}.dtype={cd}\");",
                    name = config.model.name,
                    first = config.layers[0].name,
                    fd = first_dtype,
                    cur = layer.name,
                    cd = layer.dtype
                )
                .unwrap();
            } else {
                writeln!(
                    code,
                    "// dtype check: layer {i} ({lname}) = \
                     \"{dtype}\" (matches layer 0)",
                    lname = layer.name,
                    dtype = layer.dtype
                )
                .unwrap();
            }
        }
    }
    writeln!(code).unwrap();

    // Weight naming convention validation.
    if let Some(wc) = &config.weight_convention {
        if wc.separator.is_empty() {
            writeln!(
                code,
                "const _: () = assert!(false, \
                 \"{name}: weight_convention.separator \
                 must be non-empty\");",
                name = config.model.name
            )
            .unwrap();
        }
        writeln!(
            code,
            "pub(super) const {model_id}_WEIGHT_PREFIX_COUNT: usize = {count};",
            count = wc.prefixes.len()
        )
        .unwrap();
        writeln!(
            code,
            "const _: () = assert!(\
             {model_id}_WEIGHT_PREFIX_COUNT > 0, \
             \"{name}: weight_convention.prefixes \
             must be non-empty\");",
            name = config.model.name
        )
        .unwrap();

        writeln!(
            code,
            "pub(super) const {model_id}_WEIGHT_PREFIXES: [&str; {count}] = [",
            count = wc.prefixes.len()
        )
        .unwrap();
        for prefix in &wc.prefixes {
            writeln!(code, "    \"{prefix}\",").unwrap();
        }
        writeln!(code, "];").unwrap();
    }
    writeln!(code).unwrap();
}
