// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Typed kernel descriptor — atomic bundle of compiled kernel metadata.
//!
//! [`KernelDescriptor`] ties together the MSL source, entry point, parameter
//! count, and fast-math flag into a single struct. The `#[kernel]` proc-macro
//! generates a `KernelDescriptor` constant alongside the MSL source, making it
//! impossible to accidentally pass mismatched MSL and metadata to the Metal
//! dispatch layer.

/// Atomic bundle of compiled kernel metadata generated by `#[kernel]`.
///
/// Instead of passing MSL source, entry point, param count, and fast-math flag
/// as separate arguments (where a mismatch compiles but silently corrupts), use
/// this struct to ensure all fields originate from the same kernel definition.
///
/// # Generated by proc-macro
///
/// ```text
/// #[nn_macros::kernel]
/// fn snake(x: f32, alpha: f32) -> f32 { ... }
///
/// // Generates:
/// pub const SNAKE_DESCRIPTOR: nn_dsl::KernelDescriptor = nn_dsl::KernelDescriptor::new(...);
/// ```
///
/// # Usage with Metal dispatch
///
/// ```text
/// let pipeline = KernelPipeline::from_descriptor(&cache, &SNAKE_DESCRIPTOR)?;
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub struct KernelDescriptor {
    /// MSL source text for this kernel.
    pub msl_source: &'static str,
    /// Entry point function name in the MSL source (e.g. `"snake_kernel"`).
    pub entry_point: &'static str,
    /// Number of kernel parameters (must match the MSL signature).
    pub param_count: usize,
    /// Whether fast-math optimizations are enabled for this kernel.
    pub fast_math: bool,
}

impl KernelDescriptor {
    /// Create a new kernel descriptor.
    ///
    /// This is a `const fn` so it can be used in `const` contexts (e.g.,
    /// proc-macro generated `const DESCRIPTOR: KernelDescriptor = ...`).
    #[must_use]
    pub const fn new(
        msl_source: &'static str,
        entry_point: &'static str,
        param_count: usize,
        fast_math: bool,
    ) -> Self {
        Self {
            msl_source,
            entry_point,
            param_count,
            fast_math,
        }
    }
}
