// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Snake1d kernel reference implementation and Metal codegen artifact.
//!
//! This is an end-to-end POC for issue #18:
//! - Rust reference implementation (f32 + f16)
//! - Generated MSL for Metal backends
//! - Finite-output proof-style checks for bounded domains
//! - Conservative output bounds for gamma-style verification
//!
//! # Naming convention (#336)
//!
//! - `snake_scalar` — per-element scalar, `Result<f32, KernelError>`
//! - `snake_ref_f32` / `snake_ref_f16` — vector reference, `Result<Vec<_>, KernelError>`
//! - `build_snake_scalar_kernel` — `KernelDef` IR builder (in `adain.rs`)
//!
//! ## Proof Preconditions
//!
//! nn's formal verification certificates for the snake kernel are valid
//! only when these runtime preconditions hold:
//!
//! | Precondition | Value | Enforcement |
//! |---|---|---|
//! | `alpha >= SNAKE_MIN_ALPHA` | `1e-8` | Clamped internally via `alpha.max(1e-8)` |
//! | `x` is finite | `!x.is_nan() && !x.is_infinite()` | Kani `requires` contract |
//! | `alpha` is finite | `!alpha.is_nan() && !alpha.is_infinite()` | Kani `requires` contract |
//! | `x ∈ [-1e4, 1e4]` | Verified domain | Kani `requires` contract |
//! | `alpha ∈ [0, 1e3]` | Verified domain | Kani `requires` contract |
//!
//! The alpha clamp is enforced in all code paths:
//! - **Rust reference** (`snake_scalar`): `alpha.max(SNAKE_MIN_ALPHA)` in function body
//! - **Production MSL codegen** (`build_snake_scalar_kernel`): embedded in IR
//! - **Hand-written MSL** (`emit_snake1d_msl`): `max(alpha[c], T(1e-8))`
//! - **Fused AdaIN+Snake** (`build_adain_snake_fused_kernel`): embedded in IR
//!
//! Consumers using custom GPU kernels (not generated by nn) MUST enforce
//! `alpha >= 1e-8` themselves. Without this clamp, the `1/alpha` term
//! produces infinity/NaN, and nn's proof certificates do not apply.
//!
//! ## Kani contract annotations
//!
//! Production functions use inline `#[cfg_attr(kani, kani::requires(...))]` and
//! `#[cfg_attr(kani, kani::ensures(...))]` contract annotations (ay pattern,
//! issue #30). These are complementary to the separate `#[kani::proof]`
//! harnesses in `kani_proofs` below — contracts document preconditions and
//! postconditions directly on the function signature, while harnesses verify
//! multi-step properties (bounds soundness, zero-alpha safety, monotonicity).
//!
//! Pattern:
//! ```text
//! #[cfg_attr(kani, kani::requires(x.is_finite() && x >= LO && x <= HI))]
//! #[cfg_attr(kani, kani::ensures(|result: &f32| result.is_finite()))]
//! pub fn kernel(x: f32) -> f32 { ... }
//! ```

use crate::kernel_error::KernelError;
use crate::kernel_util::{
    checked_scalar_output, validate_bounds_output, validate_bounds_pairs, validate_finite_inputs,
};

/// Minimum safe alpha value used to avoid division by zero.
pub const SNAKE_MIN_ALPHA: f32 = 1e-8;

/// Scalar Snake activation: `y = x + sin²(αx) / α`.
///
/// Alpha is clamped to [`SNAKE_MIN_ALPHA`] to prevent division by zero.
/// For the bounded domain `x ∈ [-1e4, 1e4], α ∈ [0, 1e3]` the output
/// is always finite and `>= x` (since `sin²(αx) / α >= 0` when `α > 0`,
/// and alpha is clamped to [`SNAKE_MIN_ALPHA`] internally).
///
/// ## Proof Preconditions
///
/// - `x.is_finite() && x >= -1e4 && x <= 1e4`
/// - `alpha.is_finite() && alpha >= 0.0 && alpha <= 1e3`
/// - Alpha clamped internally: `alpha.max(SNAKE_MIN_ALPHA)` (1e-8)
///
/// # Errors
///
/// Returns [`KernelError::NonFiniteInput`] if `x` or `alpha` is NaN or infinity.
/// Returns [`KernelError::NonFiniteOutput`] if the result overflows.
#[must_use = "returns a Result that may contain an error"]
#[cfg_attr(kani, kani::requires(
    x.is_finite() && alpha.is_finite()
    && x >= -1.0e4 && x <= 1.0e4
    && alpha >= 0.0 && alpha <= 1.0e3
))]
#[cfg_attr(kani, kani::ensures(|result: &Result<f32, KernelError>|
    matches!(result, Ok(v) if v.is_finite())
))]
pub fn snake_scalar(x: f32, alpha: f32) -> Result<f32, KernelError> {
    validate_finite_inputs(&[("x", x), ("alpha", alpha)])?;
    let a = alpha.max(SNAKE_MIN_ALPHA);
    let sin_val = (a * x).sin();
    checked_scalar_output(x + (1.0 / a) * sin_val * sin_val)
}

fn validate_layout(
    input_len: usize,
    alpha_len: usize,
    channels: usize,
    length: usize,
) -> Result<usize, KernelError> {
    if channels == 0 {
        return Err(KernelError::InvalidDimension {
            name: "channels",
            value: 0,
        });
    }
    if length == 0 {
        return Err(KernelError::InvalidDimension {
            name: "length",
            value: 0,
        });
    }

    let frame_size =
        channels
            .checked_mul(length)
            .ok_or_else(|| KernelError::DimensionOverflow {
                dims: format!("{channels} * {length}"),
            })?;

    if alpha_len != channels {
        return Err(KernelError::ShapeMismatch {
            expected: channels,
            got: alpha_len,
        });
    }

    if !input_len.is_multiple_of(frame_size) {
        return Err(KernelError::ShapeMismatch {
            expected: frame_size,
            got: input_len,
        });
    }

    Ok(frame_size)
}

/// Reference f32 Snake activation over a `[channels, length]` tensor.
///
/// Applies `snake_scalar` per element using the per-channel `alpha` values.
#[must_use = "returns a Result that may contain an error"]
pub fn snake_ref_f32(
    x: &[f32],
    alpha: &[f32],
    channels: usize,
    length: usize,
) -> Result<Vec<f32>, KernelError> {
    validate_layout(x.len(), alpha.len(), channels, length)?;

    let output: Result<Vec<f32>, KernelError> = x
        .iter()
        .enumerate()
        .map(|(index, value)| {
            let channel = (index / length) % channels;
            snake_scalar(*value, alpha[channel])
        })
        .collect();

    output
}

/// Reference f16 Snake activation over a `[channels, length]` tensor.
///
/// Computes in f32 then rounds back to f16 per element.
#[must_use = "returns a Result that may contain an error"]
pub fn snake_ref_f16(
    x: &[half::f16],
    alpha: &[half::f16],
    channels: usize,
    length: usize,
) -> Result<Vec<half::f16>, KernelError> {
    validate_layout(x.len(), alpha.len(), channels, length)?;

    x.iter()
        .enumerate()
        .map(|(index, value)| {
            let channel = (index / length) % channels;
            let y = snake_scalar(value.to_f32(), alpha[channel].to_f32())?;
            Ok(half::f16::from_f32(y))
        })
        .collect()
}

/// Conservative scalar output bounds for Snake over bounded x and alpha.
///
/// Given y = x + sin^2(alpha*x)/alpha and alpha > 0:
/// - sin^2(...) / alpha >= 0, so y >= x_lower
/// - sin^2(...) / alpha <= 1/alpha_lower, so y <= x_upper + 1/alpha_lower
///
/// # Convention
///
/// Uses flat `(lo, hi)` parameters per variable, matching `silu_mul_scalar_bounds`
/// and `rope_cos_scalar_bounds`. All `*_scalar_bounds` functions use this convention.
///
/// # Errors
///
/// Returns [`KernelError::NonFiniteBound`] if any input is NaN or infinity.
/// Returns [`KernelError::InvertedBounds`] if lower > upper for either pair.
#[must_use = "returns a Result that may contain an error"]
#[cfg_attr(kani, kani::requires(
    x_lo.is_finite() && x_hi.is_finite()
    && alpha_lo.is_finite() && alpha_hi.is_finite()
))]
pub fn snake_scalar_bounds(
    x_lo: f32,
    x_hi: f32,
    alpha_lo: f32,
    alpha_hi: f32,
) -> Result<(f32, f32), KernelError> {
    validate_bounds_pairs(&[(x_lo, x_hi), (alpha_lo, alpha_hi)])?;

    let safe_alpha_lower = alpha_lo.max(SNAKE_MIN_ALPHA);

    let lower = x_lo;
    // Upper bound on sin²(αx)/α is 1/α_lower since lower α gives the largest 1/α.
    let sin2_alpha_bound = 1.0_f32 / safe_alpha_lower;
    let upper = x_hi + sin2_alpha_bound;

    // Guard: overflow to infinity is possible for extreme input ranges.
    validate_bounds_output(lower, upper)
}

#[cfg(kani)]
mod kani_proofs {
    use super::*;

    fn sin_f32_stub(_x: f32) -> f32 {
        let r: f32 = kani::any();
        kani::assume(r.is_finite() && r >= -1.0 && r <= 1.0);
        r
    }

    /// Proves snake_scalar produces finite output for the issue #18 domain:
    /// x ∈ [-1e4, 1e4], alpha ∈ [1e-8, 1e3].
    ///
    /// This is the core safety property: no NaN or Inf can escape the kernel
    /// for any valid input within these bounds.
    #[kani::unwind(1)]
    #[kani::proof]
    #[kani::stub(f32::sin, sin_f32_stub)]
    fn snake_scalar_finite_for_bounded_inputs() {
        let x: f32 = kani::any();
        let alpha: f32 = kani::any();

        kani::assume(x.is_finite());
        kani::assume(alpha.is_finite());
        kani::assume(x >= -1.0e4 && x <= 1.0e4);
        kani::assume(alpha >= 1.0e-8 && alpha <= 1.0e3);

        let y = snake_scalar(x, alpha).expect("finite inputs must produce Ok");
        assert!(y.is_finite(), "snake_scalar must produce finite output");
        assert!(!y.is_nan(), "snake_scalar must not produce NaN");
    }

    /// Proves the alpha clamping prevents division by zero:
    /// even when alpha is exactly zero, the output is finite.
    #[kani::unwind(1)]
    #[kani::proof]
    #[kani::stub(f32::sin, sin_f32_stub)]
    fn snake_scalar_safe_at_zero_alpha() {
        let x: f32 = kani::any();
        kani::assume(x.is_finite());
        kani::assume(x >= -1.0e4 && x <= 1.0e4);

        let y = snake_scalar(x, 0.0).expect("finite inputs must produce Ok");
        assert!(y.is_finite(), "snake_scalar(x, 0.0) must be finite");
    }

    /// Proves snake output is always >= x (since sin²/alpha >= 0 for alpha > 0).
    #[kani::unwind(1)]
    #[kani::proof]
    #[kani::stub(f32::sin, sin_f32_stub)]
    fn snake_scalar_monotone_lower_bound() {
        let x: f32 = kani::any();
        let alpha: f32 = kani::any();

        kani::assume(x.is_finite());
        kani::assume(alpha.is_finite());
        kani::assume(x >= -100.0 && x <= 100.0);
        kani::assume(alpha >= 1.0e-8 && alpha <= 100.0);

        let y = snake_scalar(x, alpha).expect("finite inputs must produce Ok");
        // y = x + sin²(a*x)/a, and sin²/a >= 0 when a > 0
        assert!(y >= x, "snake output must be >= input");
    }

    /// Proves snake_scalar safety for the relaxed alpha domain (alpha >= 0.0,
    /// including alpha = 0), which is wider than the strict contract domain
    /// (alpha >= SNAKE_MIN_ALPHA). Internal clamping ensures the output is
    /// finite and >= x even when alpha is below SNAKE_MIN_ALPHA.
    ///
    /// NOTE: This harness does NOT prove fusion equivalence (bit-exact or
    /// approximate equality between two computation paths). It proves only
    /// safety invariants (finiteness, lower bound) for the relaxed domain.
    /// A true fusion equivalence harness would compare snake_scalar(x, alpha)
    /// against snake_scalar(x, alpha.max(SNAKE_MIN_ALPHA)) using to_bits().
    /// Renamed from fusion_equivalence_x_alpha per #97 naming rule.
    /// Written for #294 AC1.
    #[kani::unwind(8)]
    #[kani::proof]
    #[kani::stub(f32::sin, sin_f32_stub)]
    fn snake_safety_relaxed_alpha_domain() {
        let x: f32 = kani::any();
        let alpha: f32 = kani::any();

        kani::assume(x.is_finite());
        kani::assume(alpha.is_finite());
        kani::assume(x >= -1.0e4 && x <= 1.0e4);
        kani::assume(alpha >= 0.0 && alpha <= 1.0e3);

        let y = snake_scalar(x, alpha).expect("finite inputs must produce Ok");
        // The function clamps alpha internally, so the result must be finite
        // and >= x (since sin²(a*x)/a >= 0 for a > 0, and a is clamped > 0).
        assert!(
            y.is_finite(),
            "output must be finite for relaxed alpha domain"
        );
        assert!(y >= x, "snake output must be >= input for all alpha >= 0");
    }

    /// Proves conservative bounds function is sound: for any x and alpha
    /// within the bound ranges, the scalar output lies within the computed bounds.
    #[kani::unwind(8)]
    #[kani::proof]
    #[kani::stub(f32::sin, sin_f32_stub)]
    fn snake_scalar_bounds_are_sound() {
        let x: f32 = kani::any();
        let alpha: f32 = kani::any();

        kani::assume(x.is_finite());
        kani::assume(alpha.is_finite());
        // Use a tighter range for tractable Kani verification
        kani::assume(x >= -10.0 && x <= 10.0);
        kani::assume(alpha >= 0.01 && alpha <= 100.0);

        let (lower, upper) =
            snake_scalar_bounds(-10.0, 10.0, 0.01, 100.0).expect("finite bounds must succeed");
        let y = snake_scalar(x, alpha).expect("finite inputs must produce Ok");

        assert!(y >= lower, "output must be >= computed lower bound");
        assert!(y <= upper, "output must be <= computed upper bound");
    }
}

#[cfg(test)]
#[path = "snake_tests.rs"]
mod tests;
