// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Shared harness for cross-backend contract tests: verify kernel bounds via
//! NY, dispatch on Metal GPU, assert outputs within proved bounds.
//!
//! Eliminates the per-test boilerplate (compile pipeline, extract bounds,
//! build ULP margin, assertion loop) that was duplicated across 14+ tests.
//!
//! Part of #700.

/// Compile a kernel pipeline from its descriptor.
pub(crate) fn compile_pipeline(
    descriptor: &nn_dsl::KernelDescriptor,
) -> (nn_metal::PipelineCache, nn_metal::KernelPipeline) {
    // Initialize the global Metal backend so gpu_scope::get_or_create_batch()
    // can find the global context for lazy command buffer batching (#2424).
    let _ = nn_metal::MetalBackend::init().expect("Metal device required");
    let cache = nn_metal::PipelineCache::new_global().expect("Metal global cache");
    let pipeline = nn_metal::KernelPipeline::from_descriptor(&cache, descriptor)
        .expect("descriptor should compile on Metal");
    (cache, pipeline)
}

/// Verify kernel bounds via NY, dispatch on Metal GPU, assert outputs
/// fall within proved bounds (with ULP margin for FP rounding).
///
/// This is the core contract: for every sampled input, GPU output ∈ proved bounds.
///
/// # Parameters
/// - `kernel_def`: The scalar kernel IR.
/// - `descriptor`: Metal descriptor (generated by `#[kernel]` macro).
/// - `bindings`: Per-parameter `Variable` or `Constant(val)`.
/// - `variable_bounds`: Range for each `Variable` binding.
/// - `test_inputs`: GPU dispatch inputs — one slice per kernel parameter.
///   For constant params, fill with the constant value repeated `n` times.
/// - `kernel_name`: Used in assertion messages.
pub(crate) fn assert_gpu_within_verified_bounds(
    kernel_def: &nn_dsl::ir::KernelDef,
    descriptor: &nn_dsl::KernelDescriptor,
    bindings: &[nn_verify::ParamBinding],
    variable_bounds: &[(f32, f32)],
    test_inputs: &[&[f32]],
    kernel_name: &str,
) {
    // NY verification.
    let verification = nn_verify::VerifyRequest::new(kernel_def)
        .bindings(bindings)
        .variable_bounds(variable_bounds)
        .verify_bounds()
        .unwrap_or_else(|e| panic!("{kernel_name}: NY verification failed: {e}"));

    assert!(
        verification.is_finite,
        "{kernel_name}: verified bounds must be finite: [{}, {}]",
        verification.output_lower, verification.output_upper,
    );

    let proved_lower = verification.output_lower;
    let proved_upper = verification.output_upper;

    // Metal GPU dispatch.
    let (cache, pipeline) = compile_pipeline(descriptor);
    let gpu_out = pipeline
        .dispatch_elementwise(cache.context(), test_inputs)
        .unwrap_or_else(|e| panic!("{kernel_name}: Metal dispatch failed: {e}"));

    // Assert every GPU output within proved bounds (with ULP margin).
    let ulp_margin = (proved_upper - proved_lower) * f32::EPSILON;
    let safe_lower = proved_lower - ulp_margin;
    let safe_upper = proved_upper + ulp_margin;

    for (i, &g) in gpu_out.iter().enumerate() {
        assert!(
            g >= safe_lower && g <= safe_upper,
            "{kernel_name} GPU output at index {i} violates proved bounds: \
             gpu={g}, proved=[{proved_lower}, {proved_upper}], \
             safe=[{safe_lower}, {safe_upper}]",
        );
    }
}

/// Single-variable kernel with no constant parameters.
///
/// Convenience wrapper for the simplest case: one `Variable` input, no constants.
pub(crate) fn assert_single_var_contract(
    kernel_def: &nn_dsl::ir::KernelDef,
    descriptor: &nn_dsl::KernelDescriptor,
    input_range: (f32, f32),
    test_x: &[f32],
    kernel_name: &str,
) {
    let input_bounds =
        nn_verify::scalar_input_bounds(input_range.0, input_range.1).expect("scalar input bounds");

    // NY verification.
    let verification = nn_verify::VerifyRequest::new(kernel_def)
        .constant_params(&[])
        .input_bounds(&input_bounds)
        .verify_bounds()
        .unwrap_or_else(|e| panic!("{kernel_name}: NY verification failed: {e}"));

    assert!(
        verification.is_finite,
        "{kernel_name}: verified bounds must be finite: [{}, {}]",
        verification.output_lower, verification.output_upper,
    );

    let proved_lower = verification.output_lower;
    let proved_upper = verification.output_upper;

    // Metal GPU dispatch.
    let (cache, pipeline) = compile_pipeline(descriptor);
    let gpu_out = pipeline
        .dispatch_elementwise(cache.context(), &[test_x])
        .unwrap_or_else(|e| panic!("{kernel_name}: Metal dispatch failed: {e}"));

    // Assert every GPU output within proved bounds (with ULP margin).
    let ulp_margin = (proved_upper - proved_lower) * f32::EPSILON;
    let safe_lower = proved_lower - ulp_margin;
    let safe_upper = proved_upper + ulp_margin;

    for (i, &g) in gpu_out.iter().enumerate() {
        assert!(
            g >= safe_lower && g <= safe_upper,
            "{kernel_name} GPU output at index {i} violates proved bounds: \
             gpu={g}, proved=[{proved_lower}, {proved_upper}], \
             safe=[{safe_lower}, {safe_upper}]",
        );
    }
}

/// Build GPU test inputs for a multi-parameter kernel.
///
/// Given the variable test values and constant parameter values, builds
/// the `Vec<Vec<f32>>` where each constant is repeated `n` times.
/// Returns owned vectors; callers can borrow slices for `dispatch_elementwise`.
pub(crate) fn build_multi_param_inputs(test_x: &[f32], constants: &[f32]) -> Vec<Vec<f32>> {
    let n = test_x.len();
    let mut inputs = vec![test_x.to_vec()];
    for &c in constants {
        inputs.push(vec![c; n]);
    }
    inputs
}

/// Build bindings for a single-variable kernel with constant parameters.
pub(crate) fn build_bindings(constants: &[f32]) -> Vec<nn_verify::ParamBinding> {
    let mut bindings = vec![nn_verify::ParamBinding::Variable];
    bindings.extend(
        constants
            .iter()
            .map(|&c| nn_verify::ParamBinding::Constant(c)),
    );
    bindings
}

/// Combined single-variable + constants contract test.
///
/// Builds bindings and test inputs from the constant values, then runs the
/// full verify-dispatch-assert pipeline.
pub(crate) fn assert_scalar_contract(
    kernel_def: &nn_dsl::ir::KernelDef,
    descriptor: &nn_dsl::KernelDescriptor,
    constants: &[f32],
    input_range: (f32, f32),
    test_x: &[f32],
    kernel_name: &str,
) {
    let bindings = build_bindings(constants);
    let inputs = build_multi_param_inputs(test_x, constants);
    let input_refs: Vec<&[f32]> = inputs.iter().map(Vec::as_slice).collect();
    assert_gpu_within_verified_bounds(
        kernel_def,
        descriptor,
        &bindings,
        &[input_range],
        &input_refs,
        kernel_name,
    );
}
