// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Unified builder for moonshot proof certificates.
//!
//! [`FullCertificateBuilder`] composes all 8 moonshot property evidence sources
//! into a single [`MoonshotCertificate`]. This replaces the manual chaining
//! pattern where callers must know the correct order of `.with_*()` calls.
//!
//! # Usage
//!
//! ```rust,ignore
//! let cert = FullCertificateBuilder::new("dvoice-kokoro-v1", "English text", "sha256")
//!     .crown_bundle(&bundle)
//!     .timing(&timing_cert)
//!     .speaker(&speaker_evidence)
//!     .kani(&kani_evidence)
//!     .smt(&smt_evidence)
//!     .dispatch_plan(&dispatch_evidence)
//!     .build();
//! ```

use std::path::Path;

use super::{KaniVerificationEvidence, MoonshotCertificate, SmtVerificationEvidence};
use crate::moonshot_crown::{
    ImplementationCorrectnessEvidence, MoonshotCrownBundle, SpeakerConsistencyEvidence,
};
use crate::pipeline::TimingCertificate;
use crate::MoonshotStatus;

/// Unified builder for composing all 8 moonshot property proofs.
///
/// Each evidence source is optional — the builder applies only the enrichments
/// that are provided. Missing evidence leaves the corresponding property at
/// its base level from `MoonshotStatus::from_repo()`.
///
/// Enrichment order is deterministic:
/// 1. CROWN bundle (P1-P6)
/// 2. Constructive proofs for CROWN properties (P1-P4, #4254)
/// 3. Timing certificate (P5, may override CROWN's P5 result)
/// 4. Speaker evidence (P4, may override CROWN's P4 result)
/// 5. Kani evidence (P7)
/// 6. SMT evidence (P8)
/// 7. Dispatch plan correctness (P8, only upgrades)
pub struct FullCertificateBuilder<'a> {
    model_name: &'a str,
    input_specification: &'a str,
    source_hash: &'a str,
    crown_bundle: Option<&'a MoonshotCrownBundle>,
    timing_cert: Option<&'a TimingCertificate>,
    speaker_evidence: Option<&'a SpeakerConsistencyEvidence>,
    kani_evidence: Option<&'a KaniVerificationEvidence>,
    smt_evidence: Option<&'a SmtVerificationEvidence>,
    dispatch_evidence: Option<&'a ImplementationCorrectnessEvidence>,
    /// Constructive proof Lean4 sources for CROWN-based properties (P1-P4).
    ///
    /// Each entry is `(property_index, lean4_source)`. Generated by
    /// NY's `compose_crown_proofs()` or `CrownProofExport`.
    /// Attached to `PropertyCertificate::constructive_proof_lean4` in the
    /// final certificate (#4254).
    constructive_proofs: Option<&'a [(usize, String)]>,
}

impl<'a> FullCertificateBuilder<'a> {
    /// Create a new builder with required certificate metadata.
    ///
    /// # Arguments
    ///
    /// * `model_name` — Pipeline being certified (e.g., "dvoice-kokoro-v1").
    /// * `input_specification` — Input domain (e.g., "English text, ≤50 words").
    /// * `source_hash` — SHA-256 of source code at verification time.
    #[must_use]
    pub fn new(model_name: &'a str, input_specification: &'a str, source_hash: &'a str) -> Self {
        Self {
            model_name,
            input_specification,
            source_hash,
            crown_bundle: None,
            timing_cert: None,
            speaker_evidence: None,
            kani_evidence: None,
            smt_evidence: None,
            dispatch_evidence: None,
            constructive_proofs: None,
        }
    }

    /// Provide CROWN bundle evidence for P1-P6.
    #[must_use]
    pub fn crown_bundle(mut self, bundle: &'a MoonshotCrownBundle) -> Self {
        self.crown_bundle = Some(bundle);
        self
    }

    /// Provide timing certificate for P5 (temporal boundedness).
    #[must_use]
    pub fn timing(mut self, cert: &'a TimingCertificate) -> Self {
        self.timing_cert = Some(cert);
        self
    }

    /// Provide speaker consistency evidence for P4.
    #[must_use]
    pub fn speaker(mut self, evidence: &'a SpeakerConsistencyEvidence) -> Self {
        self.speaker_evidence = Some(evidence);
        self
    }

    /// Provide Kani verification evidence for P7 (memory safety).
    #[must_use]
    pub fn kani(mut self, evidence: &'a KaniVerificationEvidence) -> Self {
        self.kani_evidence = Some(evidence);
        self
    }

    /// Provide ay SMT verification evidence for P8 (correct implementation).
    #[must_use]
    pub fn smt(mut self, evidence: &'a SmtVerificationEvidence) -> Self {
        self.smt_evidence = Some(evidence);
        self
    }

    /// Provide dispatch plan correctness evidence for P8.
    ///
    /// This is complementary to SMT evidence — it checks which fraction of the
    /// pipeline's specific operations have ay-proven kernel correctness. Only
    /// upgrades P8, never downgrades.
    #[must_use]
    pub fn dispatch_plan(mut self, evidence: &'a ImplementationCorrectnessEvidence) -> Self {
        self.dispatch_evidence = Some(evidence);
        self
    }

    /// Provide constructive proof Lean4 sources for CROWN-based properties.
    ///
    /// Each entry in `proofs` is `(property_index, lean4_source)` where
    /// `property_index` is 0-based (P1=0, P2=1, P3=2, P4=3). Only CROWN-based
    /// properties (P1-P4, indices 0-3) are accepted; other indices are silently
    /// passed through to `with_constructive_proofs()`.
    ///
    /// The Lean4 source is typically generated by NY's
    /// `compose_crown_proofs()` or `CrownProofExport` (#4315, #4254).
    #[must_use]
    pub fn constructive_proofs(mut self, proofs: &'a [(usize, String)]) -> Self {
        self.constructive_proofs = Some(proofs);
        self
    }

    /// Build the complete moonshot proof certificate.
    ///
    /// Applies enrichments in deterministic order. Returns a fully-composed
    /// `MoonshotCertificate` with all provided evidence integrated.
    #[must_use]
    pub fn build(self) -> MoonshotCertificate {
        let status = MoonshotStatus::from_repo();
        let mut cert = MoonshotCertificate::from_status(
            &status,
            self.model_name,
            self.input_specification,
            self.source_hash,
        );

        // 1. CROWN bundle (P1-P6)
        if let Some(bundle) = self.crown_bundle {
            cert = cert.with_crown_results(bundle);
        }

        // 2. Constructive proofs for CROWN properties (P1-P4, #4254)
        if let Some(proofs) = self.constructive_proofs {
            cert = cert.with_constructive_proofs(proofs);
        }

        // 3. Timing certificate (P5 — may override CROWN's P5)
        if let Some(timing) = self.timing_cert {
            cert = cert.with_timing_results(timing);
        }

        // 4. Speaker evidence (P4 — may override CROWN's P4)
        if let Some(speaker) = self.speaker_evidence {
            cert = cert.with_speaker_results(speaker);
        }

        // 5. Kani evidence (P7)
        if let Some(kani) = self.kani_evidence {
            cert = cert.with_kani_results(kani);
        }

        // 6. SMT evidence (P8)
        if let Some(smt) = self.smt_evidence {
            cert = cert.with_smt_results(smt);
        }

        // 7. Dispatch plan correctness (P8 — only upgrades)
        if let Some(dispatch) = self.dispatch_evidence {
            cert = cert.with_dispatch_plan_correctness(dispatch);
        }

        cert
    }

    /// Return a summary of which evidence sources are provided.
    ///
    /// Useful for diagnostics — callers can verify they provided all intended
    /// evidence before building.
    pub fn evidence_summary(&self) -> CertificateEvidenceSummary {
        CertificateEvidenceSummary {
            has_crown: self.crown_bundle.is_some(),
            has_timing: self.timing_cert.is_some(),
            has_speaker: self.speaker_evidence.is_some(),
            has_kani: self.kani_evidence.is_some(),
            has_smt: self.smt_evidence.is_some(),
            has_dispatch_plan: self.dispatch_evidence.is_some(),
            has_constructive_proofs: self.constructive_proofs.is_some(),
            constructive_proof_count: self.constructive_proofs.map_or(0, <[(usize, String)]>::len),
            total_sources: [
                self.crown_bundle.is_some(),
                self.timing_cert.is_some(),
                self.speaker_evidence.is_some(),
                self.kani_evidence.is_some(),
                self.smt_evidence.is_some(),
                self.dispatch_evidence.is_some(),
                self.constructive_proofs.is_some(),
            ]
            .iter()
            .filter(|&&x| x)
            .count(),
        }
    }
}

/// Summary of evidence sources provided to the builder.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CertificateEvidenceSummary {
    /// CROWN bundle provided (P1-P6).
    pub has_crown: bool,
    /// Timing certificate provided (P5).
    pub has_timing: bool,
    /// Speaker evidence provided (P4).
    pub has_speaker: bool,
    /// Kani evidence provided (P7).
    pub has_kani: bool,
    /// SMT evidence provided (P8).
    pub has_smt: bool,
    /// Dispatch plan evidence provided (P8).
    pub has_dispatch_plan: bool,
    /// Constructive proof Lean4 exports provided (P1-P4, #4254).
    pub has_constructive_proofs: bool,
    /// Number of constructive proof entries provided.
    pub constructive_proof_count: usize,
    /// Total number of evidence sources provided (0-7).
    pub total_sources: usize,
}

/// Convenience function to build a complete 8-property certificate from all
/// available evidence.
///
/// This is the highest-level entry point for certificate generation. It
/// creates a `FullCertificateBuilder`, attaches all evidence, and builds.
///
/// # Arguments
///
/// * `model_name` — Pipeline being certified.
/// * `input_specification` — Input domain description.
/// * `source_hash` — SHA-256 of source code at verification time.
/// * `crown_bundle` — CROWN results for P1-P6.
/// * `kani_evidence` — Kani results for P7.
/// * `smt_evidence` — ay SMT results for P8.
/// * `dispatch_evidence` — Dispatch plan analysis for P8 (complementary).
pub fn build_full_certificate(
    model_name: &str,
    input_specification: &str,
    source_hash: &str,
    crown_bundle: &MoonshotCrownBundle,
    kani_evidence: &KaniVerificationEvidence,
    smt_evidence: &SmtVerificationEvidence,
    dispatch_evidence: Option<&ImplementationCorrectnessEvidence>,
) -> MoonshotCertificate {
    let mut builder = FullCertificateBuilder::new(model_name, input_specification, source_hash)
        .crown_bundle(crown_bundle)
        .kani(kani_evidence)
        .smt(smt_evidence);

    if let Some(dispatch) = dispatch_evidence {
        builder = builder.dispatch_plan(dispatch);
    }

    builder.build()
}

/// Convenience function to build a complete 8-property certificate with all
/// evidence sources including timing, speaker, and attention.
///
/// This is the "everything" entry point used when all 6 evidence sources are
/// available. For partial evidence, use [`FullCertificateBuilder`] directly.
pub fn build_full_certificate_with_all_evidence(
    model_name: &str,
    input_specification: &str,
    source_hash: &str,
    crown_bundle: &MoonshotCrownBundle,
    timing_cert: &TimingCertificate,
    speaker_evidence: &SpeakerConsistencyEvidence,
    kani_evidence: &KaniVerificationEvidence,
    smt_evidence: &SmtVerificationEvidence,
    dispatch_evidence: &ImplementationCorrectnessEvidence,
) -> MoonshotCertificate {
    FullCertificateBuilder::new(model_name, input_specification, source_hash)
        .crown_bundle(crown_bundle)
        .timing(timing_cert)
        .speaker(speaker_evidence)
        .kani(kani_evidence)
        .smt(smt_evidence)
        .dispatch_plan(dispatch_evidence)
        .build()
}

/// Build a certificate with P7 evidence sourced from `kani_status.json` and
/// workspace scan, using [`KaniVerificationEvidence::from_kani_status_or_scan`].
///
/// This is the recommended entry point when Kani results live on disk rather
/// than being pre-constructed. The function reads `kani_status.json` for
/// actual pass/fail results and falls back to a workspace source scan if the
/// file is unavailable.
///
/// # Arguments
///
/// * `model_name` — Pipeline being certified.
/// * `input_specification` — Input domain description.
/// * `source_hash` — SHA-256 of source code at verification time.
/// * `kani_status_path` — Path to `kani_status.json`.
/// * `crates_dir` — Path to workspace `crates/` directory for harness scan.
/// * `assume_all_pass_fallback` — If `kani_status.json` is unavailable and
///   falling back to workspace scan, whether to assume all harnesses pass.
/// * `crown_bundle` — CROWN results for P1-P6 (optional).
/// * `smt_evidence` — ay SMT results for P8 (optional).
/// * `dispatch_evidence` — Dispatch plan analysis for P8 (optional).
pub fn build_certificate_from_workspace(
    model_name: &str,
    input_specification: &str,
    source_hash: &str,
    kani_status_path: &Path,
    crates_dir: &Path,
    assume_all_pass_fallback: bool,
    crown_bundle: Option<&MoonshotCrownBundle>,
    smt_evidence: Option<&SmtVerificationEvidence>,
    dispatch_evidence: Option<&ImplementationCorrectnessEvidence>,
) -> MoonshotCertificate {
    let kani_evidence = KaniVerificationEvidence::from_kani_status_or_scan(
        kani_status_path,
        crates_dir,
        assume_all_pass_fallback,
    );

    let mut builder = FullCertificateBuilder::new(model_name, input_specification, source_hash)
        .kani(&kani_evidence);

    if let Some(crown) = crown_bundle {
        builder = builder.crown_bundle(crown);
    }
    if let Some(smt) = smt_evidence {
        builder = builder.smt(smt);
    }
    if let Some(dispatch) = dispatch_evidence {
        builder = builder.dispatch_plan(dispatch);
    }

    builder.build()
}

impl std::fmt::Display for CertificateEvidenceSummary {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Evidence: {}/7 sources (CROWN={}, timing={}, speaker={}, Kani={}, SMT={}, dispatch={}, proofs={}({}))",
            self.total_sources,
            if self.has_crown { "Y" } else { "N" },
            if self.has_timing { "Y" } else { "N" },
            if self.has_speaker { "Y" } else { "N" },
            if self.has_kani { "Y" } else { "N" },
            if self.has_smt { "Y" } else { "N" },
            if self.has_dispatch_plan { "Y" } else { "N" },
            if self.has_constructive_proofs { "Y" } else { "N" },
            self.constructive_proof_count,
        )
    }
}
