// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Moonshot proof certificate types.
//!
//! [`MoonshotCertificate`] is the serializable bundle that captures all 8
//! property verification levels, proof artifacts, and assumptions. It is the
//! machine-checkable artifact shipped alongside model deployments.

use serde::{Deserialize, Serialize};

use super::{MoonshotStatus, VerificationLevel};

/// Evidence bundle for Property 7 (memory safety) from Kani harness results.
///
/// Captures the aggregate Kani verification status: how many harnesses
/// passed, total count, and which artifact files contain the harnesses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KaniVerificationEvidence {
    /// Number of Kani harnesses that passed.
    pub harnesses_passed: usize,
    /// Total number of Kani harnesses.
    pub harnesses_total: usize,
    /// File paths to Kani harness source files (relative to repo root).
    pub harness_files: Vec<String>,
    /// Whether all harnesses passed without timeout or failure.
    pub all_passed: bool,
}

/// Evidence bundle for Property 8 (correct implementation) from ay SMT results.
///
/// Captures the aggregate ay verification status: how many kernel proofs
/// reached `Proven`, and which kernel names were verified.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SmtVerificationEvidence {
    /// Number of kernel proofs that reached `Proven`.
    pub kernels_proven: usize,
    /// Total number of kernel proofs attempted.
    pub kernels_total: usize,
    /// Names of kernels that reached `Proven`.
    pub proven_kernel_names: Vec<String>,
    /// Whether all kernel proofs reached `Proven`.
    pub all_proven: bool,
}

/// A sub-condition result attached to a primary property certificate.
///
/// When multiple CROWN checks share the same `property_index` (e.g.,
/// `check_temporal_boundedness` and `check_memory_boundedness` both target
/// property 4), the primary result writes `bound_value`/`threshold` and
/// subsequent results are stored here to avoid overwriting incomparable
/// quantities (e.g., microseconds vs bytes).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubCondition {
    /// Human-readable name of the sub-condition (e.g., "memory_boundedness").
    pub name: String,
    /// Bound value for this sub-condition.
    pub bound_value: f64,
    /// Threshold for this sub-condition.
    pub threshold: f64,
    /// Whether this sub-condition is proven.
    pub proven: bool,
    /// Human-readable explanation.
    pub explanation: String,
}

/// Proof certificate for a single moonshot property.
///
/// Each property has a verification level, proof artifact paths,
/// and any assumptions under which the proof holds.
#[derive(Debug, Clone, Serialize)]
pub struct PropertyCertificate {
    /// Property index (0-7).
    pub property_index: usize,
    /// Human-readable property name.
    pub property_name: &'static str,
    /// Verification level achieved.
    pub level: VerificationLevel,
    /// File paths to proof artifacts (relative to repo root).
    pub proof_artifacts: Vec<String>,
    /// Assumptions under which this proof holds.
    pub assumptions: Vec<String>,
    /// Numerical bound value (if applicable, e.g., output range for non-clipping).
    pub bound_value: Option<f64>,
    /// Threshold the bound must meet (if applicable).
    pub threshold: Option<f64>,
    /// Sub-condition results that share this property index but have
    /// different bound semantics (e.g., memory boundedness under P5).
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub sub_results: Vec<SubCondition>,
    /// Constructive proof Lean4 source for CROWN-based properties (P1-P4).
    ///
    /// When present, contains a self-contained Lean4 module that an auditor
    /// can check with the Lean4 proof checker to independently verify the
    /// bound claimed by this property. Generated by NY's
    /// `compose_crown_proofs()` or `CrownProofExport` (#4315).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub constructive_proof_lean4: Option<String>,
}

/// Current certificate schema version. Increment when the format changes.
/// - v1: initial format (2026-03-10)
/// - v2: added schema_version, dynamic verification_date (2026-03-11)
/// - v3: added sub_results to PropertyCertificate (#1925) (2026-03-11)
/// - v4: added constructive_proof_lean4 to PropertyCertificate,
///   constructive_proof_count to MoonshotCertificate (#4315) (2026-04-01)
pub const CERTIFICATE_SCHEMA_VERSION: u32 = 4;

/// Unified certificate combining all 8 moonshot property proofs.
///
/// This is the machine-checkable artifact that proves (or documents progress
/// toward proving) that a TTS pipeline satisfies all 8 formal properties.
///
/// # Serialization
///
/// The certificate is designed to be serializable to JSON for archival
/// and external audit. Use [`MoonshotCertificate::to_json()`] for output.
#[derive(Debug, Clone, Serialize)]
pub struct MoonshotCertificate {
    /// Schema version for forward/backward compatibility.
    ///
    /// Increment when the certificate format changes. Consumers can use
    /// this to detect incompatible certificates from older/newer versions.
    /// - v1: initial format (2026-03-10)
    /// - v2: added schema_version, dynamic verification_date (2026-03-11)
    pub schema_version: u32,
    /// Model pipeline being certified (e.g., "dvoice-kokoro-v1").
    pub model_name: String,
    /// Input specification (e.g., "English text, ≤50 words").
    pub input_specification: String,
    /// Per-property proof certificates.
    pub properties: Vec<PropertyCertificate>,
    /// SHA-256 hash of the source code at verification time.
    pub source_hash: String,
    /// ISO 8601 date of certificate generation.
    pub verification_date: String,
    /// Dimension used for CROWN verification (if per-layer CROWN was used).
    pub verification_dim: Option<usize>,
    /// Whether all 8 properties are at least CrownPartial.
    pub all_at_least_partial: bool,
    /// Whether all 8 properties are fully proven (CrownProven, KaniProven, or SmtProven).
    pub all_proven: bool,
    /// Number of properties with constructive proof Lean4 exports (#4315).
    ///
    /// Counts how many `PropertyCertificate` entries have
    /// `constructive_proof_lean4.is_some()`. A fully-certified pipeline
    /// has constructive proofs for all CROWN-based properties (P1-P4).
    pub constructive_proof_count: usize,
}

impl MoonshotCertificate {
    /// Build a certificate from the current repo state.
    ///
    /// Scans the artifact registry and constructs per-property certificates
    /// from the existing verification evidence.
    pub fn from_status(
        status: &MoonshotStatus,
        model_name: &str,
        input_specification: &str,
        source_hash: &str,
    ) -> Self {
        let properties: Vec<PropertyCertificate> = status
            .properties
            .iter()
            .enumerate()
            .map(|(i, prop)| PropertyCertificate {
                property_index: i,
                property_name: prop.name,
                level: prop.verified,
                proof_artifacts: prop.evidence.iter().map(|s| (*s).to_string()).collect(),
                assumptions: if prop.verified >= VerificationLevel::CrownPartial {
                    vec!["Input within specified bounds".to_string()]
                } else {
                    vec!["Empirical testing only — no formal guarantee".to_string()]
                },
                bound_value: None,
                threshold: None,
                sub_results: vec![],
                constructive_proof_lean4: None,
            })
            .collect();

        let all_at_least_partial = status.all_at_least_crown_partial();
        let all_proven = properties.iter().all(|p| {
            matches!(
                p.level,
                VerificationLevel::CrownProven
                    | VerificationLevel::KaniProven
                    | VerificationLevel::SmtProven
            )
        });

        let constructive_proof_count = properties
            .iter()
            .filter(|p| p.constructive_proof_lean4.is_some())
            .count();

        Self {
            schema_version: CERTIFICATE_SCHEMA_VERSION,
            model_name: model_name.to_string(),
            input_specification: input_specification.to_string(),
            properties,
            source_hash: source_hash.to_string(),
            verification_date: display::current_date(),
            verification_dim: None,
            all_at_least_partial,
            all_proven,
            constructive_proof_count,
        }
    }
}

// Enrichment methods (with_crown_results, with_timing_results, etc.)
// extracted to moonshot_certificate_enrichment.rs (#1940).
#[path = "moonshot_certificate_enrichment.rs"]
mod enrichment;

#[path = "moonshot_certificate_serde.rs"]
mod serde_support;
pub use serde_support::CertificateDeserializeError;

#[path = "moonshot_certificate_builder.rs"]
mod builder;
pub use builder::{
    build_certificate_from_workspace, build_full_certificate,
    build_full_certificate_with_all_evidence, CertificateEvidenceSummary, FullCertificateBuilder,
};

#[path = "moonshot_certificate_display.rs"]
mod display;

#[path = "moonshot_evidence_bridge.rs"]
mod evidence_bridge;

#[path = "moonshot_certificate_validate.rs"]
mod validate;
pub use validate::{
    validate_certificate, CertificateValidation, FindingSeverity, ValidationFinding,
};

#[path = "moonshot_certificate_source_hash.rs"]
mod source_hash;
pub use source_hash::{compute_workspace_source_hash, is_valid_sha256_hex, SourceHashError};

#[cfg(test)]
#[path = "moonshot_certificate_tests.rs"]
mod certificate_tests;

#[cfg(test)]
#[path = "moonshot_certificate_builder_tests.rs"]
mod builder_tests;

#[cfg(test)]
#[path = "moonshot_certificate_serde_tests.rs"]
mod serde_tests;

#[cfg(test)]
#[path = "moonshot_certificate_serde_validate_tests.rs"]
mod serde_validate_tests;

#[cfg(test)]
#[path = "moonshot_certificate_validate_tests.rs"]
mod validate_tests;
