// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Quantization verification certificates for TTS models.
//!
//! Proves that quantizing a model (e.g., f32 → bf16) preserves audio quality
//! for ALL inputs, not just a test set. The approach:
//!
//! 1. Run NY bounds propagation on the f32 model → f32 output bounds.
//! 2. Run NY on the bf16-quantized model (weights rounded to bf16
//!    then widened back to f32) → bf16 output bounds.
//! 3. Compute the quantization drift: per-element Hausdorff distance between
//!    f32 and bf16 output intervals.
//! 4. Feed the max drift into Lipschitz quality bound machinery to prove
//!    quality metrics (MCD, SNR, cosine similarity) remain within thresholds.
//!
//! The key insight: bf16 quantization only affects model weights, not the
//! propagation method. Both models share the same input domain. The output
//! drift measures how much weight rounding shifts the output intervals.
//!
//! # Drift Computation
//!
//! For output element `i`, the pointwise drift between f32 and bf16 models is:
//!
//!   drift_i = max(|lo_bf16_i - lo_f32_i|, |hi_bf16_i - hi_f32_i|)
//!
//! This bounds `|y_f32(x) - y_bf16(x)|` for any input `x` in the perturbation
//! set. The aggregate drift (L∞) is `max_i(drift_i)`.
//!
//! Part of #2464.
//! Part of #2218.
//!
//! # References
//!
//! - Design: `designs/2026-03-15-perfect-kokoro-faster-than-mlx.md` (Phase 3E)
//! - Lipschitz composition: `quality_bound.rs`

use crate::error::{DspErrorKind, TtsVerifyError};
use crate::quality_bound::{verify_quality_bounds, QualityBoundCertificate, QualityMetricSpec};

/// Per-segment comparison of f32 vs quantized output bounds.
#[derive(Debug, Clone)]
pub struct QuantizationSegmentResult {
    /// Segment name (e.g., "bert_encoder", "text_encoder").
    pub segment_name: String,
    /// F32 output bound width: max(hi) - min(lo) across all elements.
    pub f32_output_width: f64,
    /// Quantized output bound width: max(hi) - min(lo) across all elements.
    pub quantized_output_width: f64,
    /// F32 output bounds: (global_min_lower, global_max_upper).
    pub f32_bounds: (f64, f64),
    /// Quantized output bounds: (global_min_lower, global_max_upper).
    pub quantized_bounds: (f64, f64),
    /// Per-element max drift: max_i max(|lo_q_i - lo_f_i|, |hi_q_i - hi_f_i|).
    pub max_element_drift: f64,
    /// Mean element drift across all output elements.
    pub mean_element_drift: f64,
    /// Number of output elements compared.
    pub num_elements: usize,
}

/// Certificate proving quantization preserves audio quality for all inputs.
///
/// Generated by comparing NY output bounds between f32 and quantized
/// models, then applying Lipschitz composition to prove quality metrics hold.
#[derive(Debug, Clone)]
pub struct QuantizationCertificate {
    /// Source dtype name (e.g., "F32").
    pub source_dtype: String,
    /// Target dtype name (e.g., "BF16").
    pub target_dtype: String,
    /// Per-segment bound comparison results.
    pub segment_results: Vec<QuantizationSegmentResult>,
    /// Maximum quantization-induced output drift across all segments.
    pub max_output_drift: f64,
    /// Quality bound certificate using the max drift as perturbation width.
    pub quality_certificate: QualityBoundCertificate,
    /// Whether all quality metrics are guaranteed to hold despite quantization.
    pub quality_preserved: bool,
}

/// Compute per-element drift between f32 and quantized output bounds.
///
/// For each output element, computes:
///   drift_i = max(|lo_q_i - lo_f_i|, |hi_q_i - hi_f_i|)
///
/// Returns `(max_drift, mean_drift, num_elements)`.
///
/// # Errors
///
/// Returns error if the bound arrays have different lengths or contain
/// non-finite values.
pub fn compute_element_drift(
    f32_lower: &[f32],
    f32_upper: &[f32],
    quant_lower: &[f32],
    quant_upper: &[f32],
) -> Result<(f64, f64, usize), TtsVerifyError> {
    if f32_lower.len() != f32_upper.len()
        || f32_lower.len() != quant_lower.len()
        || f32_lower.len() != quant_upper.len()
    {
        return Err(TtsVerifyError::DimensionMismatch {
            expected: f32_lower.len(),
            actual: quant_lower.len(),
            context: "quantization drift: f32 and quantized bounds must have same length",
        });
    }

    let n = f32_lower.len();
    if n == 0 {
        return Err(TtsVerifyError::Dsp(DspErrorKind::EmptyInput {
            what: "quantization drift: empty bounds arrays",
        }));
    }

    let mut max_drift: f64 = 0.0;
    let mut sum_drift: f64 = 0.0;

    for i in 0..n {
        let fl = f64::from(f32_lower[i]);
        let fh = f64::from(f32_upper[i]);
        let ql = f64::from(quant_lower[i]);
        let qh = f64::from(quant_upper[i]);

        if !fl.is_finite() || !fh.is_finite() || !ql.is_finite() || !qh.is_finite() {
            return Err(TtsVerifyError::Dsp(DspErrorKind::Computation {
                what: "quantization drift: non-finite bound element",
            }));
        }

        let drift = (ql - fl).abs().max((qh - fh).abs());
        max_drift = max_drift.max(drift);
        sum_drift += drift;
    }

    let mean_drift = sum_drift / n as f64;
    Ok((max_drift, mean_drift, n))
}

/// Build a `QuantizationSegmentResult` from f32 and quantized output bounds.
///
/// # Arguments
///
/// * `segment_name` — Human-readable segment identifier.
/// * `f32_lower`, `f32_upper` — F32 model output bounds (from IBP/CROWN).
/// * `quant_lower`, `quant_upper` — Quantized model output bounds.
pub fn build_segment_result(
    segment_name: &str,
    f32_lower: &[f32],
    f32_upper: &[f32],
    quant_lower: &[f32],
    quant_upper: &[f32],
) -> Result<QuantizationSegmentResult, TtsVerifyError> {
    let (max_drift, mean_drift, num_elements) =
        compute_element_drift(f32_lower, f32_upper, quant_lower, quant_upper)?;

    let f32_lo_min = f64::from(f32_lower.iter().copied().fold(f32::INFINITY, f32::min));
    let f32_hi_max = f64::from(f32_upper.iter().copied().fold(f32::NEG_INFINITY, f32::max));
    let q_lo_min = f64::from(quant_lower.iter().copied().fold(f32::INFINITY, f32::min));
    let q_hi_max = f64::from(
        quant_upper
            .iter()
            .copied()
            .fold(f32::NEG_INFINITY, f32::max),
    );

    Ok(QuantizationSegmentResult {
        segment_name: segment_name.to_string(),
        f32_output_width: f32_hi_max - f32_lo_min,
        quantized_output_width: q_hi_max - q_lo_min,
        f32_bounds: (f32_lo_min, f32_hi_max),
        quantized_bounds: (q_lo_min, q_hi_max),
        max_element_drift: max_drift,
        mean_element_drift: mean_drift,
        num_elements,
    })
}

/// Build a `QuantizationCertificate` from segment results and quality specs.
///
/// Takes the per-segment drift results and quality metric specifications,
/// uses the maximum drift across all segments as the perturbation width
/// for Lipschitz quality bound verification.
///
/// # Arguments
///
/// * `source_dtype` — Source dtype name (e.g., "F32").
/// * `target_dtype` — Target dtype name (e.g., "BF16").
/// * `segments` — Per-segment bound comparison results.
/// * `quality_specs` — Quality metrics with Lipschitz constants and baselines.
pub fn build_quantization_certificate(
    source_dtype: &str,
    target_dtype: &str,
    segments: Vec<QuantizationSegmentResult>,
    quality_specs: &[QualityMetricSpec],
) -> Result<QuantizationCertificate, TtsVerifyError> {
    if segments.is_empty() {
        return Err(TtsVerifyError::Dsp(DspErrorKind::EmptyInput {
            what: "quantization certificate requires at least one segment result",
        }));
    }

    let max_output_drift = segments
        .iter()
        .map(|s| s.max_element_drift)
        .fold(0.0f64, f64::max);

    let quality_certificate = verify_quality_bounds(max_output_drift, quality_specs)?;
    let quality_preserved = quality_certificate.all_guaranteed;

    Ok(QuantizationCertificate {
        source_dtype: source_dtype.to_string(),
        target_dtype: target_dtype.to_string(),
        segment_results: segments,
        max_output_drift,
        quality_certificate,
        quality_preserved,
    })
}

#[cfg(test)]
#[path = "quantization_certificate_tests.rs"]
mod tests;

#[cfg(kani)]
#[path = "quantization_certificate_kani.rs"]
mod kani_proofs;
