// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! Generate `compile_<name>()` and `compile_verified_<name>()` companion
//! functions for `#[nn::model]`-annotated model functions.
//!
//! Only emits code when the model has at least one `DynTensor` parameter.
//! Scalar-only models (f32, Tensor<D>) get no compile functions (Phase 1).
//!
//! Part of #3051, #3020.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Check if a type contains `DynTensor` (owned or referenced).
fn is_dyn_tensor(ty: &syn::Type) -> bool {
    let ty_str = quote!(#ty).to_string();
    ty_str.contains("DynTensor")
}

/// Check if a type is a reference (`&T` or `&mut T`).
fn is_reference(ty: &syn::Type) -> bool {
    matches!(ty, syn::Type::Reference(_))
}

/// Generate `compile_<name>()` and `compile_verified_<name>()` for a model.
///
/// Returns empty `TokenStream` for scalar-only models (no DynTensor params).
pub(crate) fn generate_compile_fns(func: &syn::ItemFn) -> TokenStream {
    let func_name = &func.sig.ident;

    // Classify parameters into tensor (DynTensor) vs forwarded (everything else).
    let mut tensor_count: usize = 0;
    let mut forwarded_sig_params = Vec::new();
    let mut call_args = Vec::new();

    for input in &func.sig.inputs {
        let pat_ty = match input {
            syn::FnArg::Typed(pt) => pt,
            _ => continue,
        };
        let name = match &*pat_ty.pat {
            syn::Pat::Ident(pi) => &pi.ident,
            _ => continue,
        };

        if is_dyn_tensor(&pat_ty.ty) {
            let idx = syn::Index::from(tensor_count);
            tensor_count += 1;
            if is_reference(&pat_ty.ty) {
                call_args.push(quote! { inputs[#idx] });
            } else {
                call_args.push(quote! { inputs[#idx].clone() });
            }
        } else {
            let ty = &pat_ty.ty;
            forwarded_sig_params.push(quote! { #name: #ty });
            call_args.push(quote! { #name });
        }
    }

    if tensor_count == 0 {
        return quote! {};
    }

    let compile_fn_name = format_ident!("compile_{}", func_name);
    let verified_fn_name = format_ident!("compile_verified_{}", func_name);
    let expect_msg = format!("{func_name} expects {tensor_count} tensor input(s)");

    let compile_fn = quote! {
        /// Trace and compile this model for GPU execution.
        ///
        /// Auto-generated by `#[nn::model]`. Returns a
        /// [`CompiledModel`](nn_metal::compiled_model::CompiledModel) that can be executed
        /// repeatedly without re-tracing.
        #[cfg(target_os = "macos")]
        pub fn #compile_fn_name(
            inputs: &[&nn_core::dyn_tensor::DynTensor],
            #(#forwarded_sig_params,)*
            cache: &nn_metal::PipelineCache,
        ) -> nn_core::Result<nn_metal::compiled_model::CompiledModel> {
            assert_eq!(inputs.len(), #tensor_count, #expect_msg);
            let (_, graph) = nn_core::dyn_tensor::trace::trace_graph(|| {
                #func_name(#(#call_args),*)
            })?;
            nn_metal::compiled_model::CompiledModel::builder(&graph, cache).build()
        }
    };

    let compile_verified_fn = quote! {
        /// Trace, compile, and verify this model with a proof certificate.
        ///
        /// Auto-generated by `#[nn::model]`. Returns a
        /// [`VerifiedModel`](nn_verify::VerifiedModel) pairing the compiled
        /// model with its certification result.
        #[cfg(all(target_os = "macos", feature = "verify"))]
        pub fn #verified_fn_name(
            inputs: &[&nn_core::dyn_tensor::DynTensor],
            #(#forwarded_sig_params,)*
            cache: &nn_metal::PipelineCache,
            bounds: &nn_verify::BoundedTensor,
            config: &nn_verify::CertifyConfig,
        ) -> nn_core::Result<nn_verify::VerifiedModel<nn_metal::compiled_model::CompiledModel>> {
            assert_eq!(inputs.len(), #tensor_count, #expect_msg);
            let (_, graph) = nn_core::dyn_tensor::trace::trace_graph(|| {
                #func_name(#(#call_args),*)
            })?;
            let compiled = nn_metal::compiled_model::CompiledModel::builder(&graph, cache).build()?;
            nn_verify::verify_compiled(compiled, &graph, bounds, config)
                .map_err(|e| nn_core::TensorError::from(
                    nn_metal::compiled_model::CompiledModelError::CertifyFailed(e),
                ))
        }
    };

    quote! {
        #compile_fn
        #compile_verified_fn
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_dyn_tensor_owned() {
        let ty: syn::Type = syn::parse_str("DynTensor").unwrap();
        assert!(is_dyn_tensor(&ty));
    }

    #[test]
    fn test_is_dyn_tensor_ref() {
        let ty: syn::Type = syn::parse_str("&DynTensor").unwrap();
        assert!(is_dyn_tensor(&ty));
    }

    #[test]
    fn test_is_dyn_tensor_qualified() {
        let ty: syn::Type = syn::parse_str("nn_core::dyn_tensor::DynTensor").unwrap();
        assert!(is_dyn_tensor(&ty));
    }

    #[test]
    fn test_is_not_dyn_tensor() {
        let ty: syn::Type = syn::parse_str("f32").unwrap();
        assert!(!is_dyn_tensor(&ty));
    }

    #[test]
    fn test_is_not_dyn_tensor_var_builder() {
        let ty: syn::Type = syn::parse_str("&VarBuilder").unwrap();
        assert!(!is_dyn_tensor(&ty));
    }

    #[test]
    fn test_is_dyn_tensor_mut_ref() {
        let ty: syn::Type = syn::parse_str("&mut DynTensor").unwrap();
        assert!(is_dyn_tensor(&ty));
    }

    /// Type aliases like `type Tensor = DynTensor` are NOT detected.
    /// This is inherent to proc-macros (cannot resolve type aliases).
    /// Users must use `DynTensor` directly in `#[nn::model]` signatures.
    #[test]
    fn test_type_alias_is_false_negative() {
        let ty: syn::Type = syn::parse_str("Tensor").unwrap();
        assert!(!is_dyn_tensor(&ty));
    }

    /// Container types match (string contains "DynTensor") but generate
    /// wrong code. The Rust compiler catches this at the use site (type
    /// mismatch on `inputs[idx]`), so it's a confusing-error not a silent bug.
    #[test]
    fn test_container_type_matches_string() {
        let ty: syn::Type = syn::parse_str("Vec<DynTensor>").unwrap();
        assert!(is_dyn_tensor(&ty), "string match catches containers");
    }

    #[test]
    fn test_scalar_model_produces_empty() {
        let func: syn::ItemFn =
            syn::parse_str("fn nn_model(x: f32, y: f32) -> f32 { x + y }").unwrap();
        let tokens = generate_compile_fns(&func);
        assert!(
            tokens.is_empty(),
            "scalar model should not generate compile fns"
        );
    }
}
